"""
Desk Scheduler — Proactive scheduled tasks for AI desks.
Runs background checks at defined intervals to catch overdue items,
generate daily reports, and trigger autonomous desk operations.
"""
import asyncio
import logging
from datetime import datetime

logger = logging.getLogger("max.desks.scheduler")

# Schedule: (hour, minute, task_name, description)
DAILY_SCHEDULE = [
    (8, 30, "check_overdue_invoices", "Finance: Check for overdue invoices"),
    (9, 0, "check_overdue_followups", "Forge: Check overdue customer follow-ups"),
    (9, 30, "audit_open_tickets", "Support: Audit open support tickets"),
    (10, 0, "draft_social_post", "Marketing: Draft daily social media post"),
]


class DeskScheduler:
    """Runs proactive scheduled tasks for AI desks."""

    def __init__(self):
        self._running = False
        self._last_run: dict[str, str] = {}  # task_name → last run date

    async def start(self):
        """Start the scheduler loop."""
        self._running = True
        logger.info("Desk scheduler started")

        while self._running:
            try:
                now = datetime.now()
                today = now.strftime("%Y-%m-%d")

                for hour, minute, task_name, description in DAILY_SCHEDULE:
                    # Check if it's time and hasn't run today
                    if (
                        now.hour == hour
                        and now.minute == minute
                        and self._last_run.get(task_name) != today
                    ):
                        self._last_run[task_name] = today
                        asyncio.create_task(self._run_scheduled_task(task_name, description))

            except Exception as e:
                logger.warning(f"Scheduler tick error: {e}")

            await asyncio.sleep(60)  # Check every minute

    def stop(self):
        self._running = False
        logger.info("Desk scheduler stopped")

    async def _run_scheduled_task(self, task_name: str, description: str):
        """Execute a scheduled task by submitting it to the desk system."""
        import httpx

        logger.info(f"Running scheduled task: {task_name}")
        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                resp = await client.post(
                    "http://localhost:8000/api/v1/max/ai-desks/tasks",
                    json={
                        "title": description,
                        "description": f"Scheduled daily task: {description}. Auto-generated by desk scheduler.",
                        "priority": "normal",
                        "source": "scheduler",
                    },
                )
                if resp.status_code == 200:
                    data = resp.json()
                    logger.info(f"Scheduled task submitted: {task_name} → {data.get('task_id', 'unknown')}")
                else:
                    logger.warning(f"Scheduled task {task_name} failed: {resp.status_code}")
        except Exception as e:
            logger.warning(f"Scheduled task {task_name} error: {e}")


# Singleton
desk_scheduler = DeskScheduler()
