'use client';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import { Message } from '@/lib/types';
import { ToolResultCard } from '@/components/desks/shared';
import { Copy, Check, Brain, Volume2, Square, Loader2, Printer, FileDown, Send, Share2 } from 'lucide-react';
import { useState, useRef, useCallback } from 'react';
import { API_URL } from '@/lib/api';

function ShareMenu({ content, toolResults }: { content: string; toolResults?: any[] }) {
  const [open, setOpen] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const menuRef = useRef<HTMLDivElement>(null);

  const showStatus = (msg: string) => {
    setStatus(msg);
    setTimeout(() => setStatus(null), 2500);
  };

  const copyFull = () => {
    navigator.clipboard.writeText(content);
    showStatus('Copied');
    setOpen(false);
  };

  const printMessage = () => {
    setOpen(false);
    const win = window.open('', '_blank', 'width=800,height=600');
    if (!win) return;
    win.document.write(`<!DOCTYPE html><html><head><title>MAX Response</title>
<style>
body{font-family:system-ui,sans-serif;max-width:700px;margin:40px auto;padding:0 20px;color:#1a1a1a;line-height:1.6}
h1,h2,h3{color:#333}table{border-collapse:collapse;width:100%;margin:12px 0}
th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f5f5f5}
pre{background:#f5f5f5;padding:12px;border-radius:6px;overflow-x:auto;font-size:13px}
code{font-family:'JetBrains Mono',monospace}
.header{display:flex;align-items:center;gap:10px;margin-bottom:20px;padding-bottom:12px;border-bottom:2px solid #D4AF37}
.logo{width:32px;height:32px;border-radius:50%;background:linear-gradient(135deg,#D4AF37,#8B5CF6);display:flex;align-items:center;justify-content:center;color:#fff;font-weight:bold;font-size:14px}
.footer{margin-top:30px;padding-top:12px;border-top:1px solid #ddd;font-size:12px;color:#888}
</style></head><body>
<div class="header"><div class="logo">M</div><div><strong>MAX AI Assistant</strong><br><span style="font-size:12px;color:#888">${new Date().toLocaleString()}</span></div></div>
<div id="content"></div>
<div class="footer">Generated by MAX AI — Empire Management System</div>
</body></html>`);
    // Render markdown as HTML
    const div = win.document.getElementById('content')!;
    div.innerHTML = markdownToHtml(content);
    win.document.close();
    setTimeout(() => win.print(), 300);
  };

  const exportPdf = async () => {
    setOpen(false);
    showStatus('Generating PDF...');
    // Use print-to-PDF via a hidden iframe approach
    const iframe = document.createElement('iframe');
    iframe.style.position = 'fixed';
    iframe.style.left = '-9999px';
    iframe.style.width = '800px';
    iframe.style.height = '600px';
    document.body.appendChild(iframe);
    const doc = iframe.contentDocument!;
    doc.open();
    doc.write(`<!DOCTYPE html><html><head><title>MAX Response</title>
<style>
body{font-family:system-ui,sans-serif;max-width:700px;margin:30px auto;padding:0 20px;color:#1a1a1a;line-height:1.6}
h1,h2,h3{color:#333}table{border-collapse:collapse;width:100%;margin:12px 0}
th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#f5f5f5}
pre{background:#f5f5f5;padding:12px;border-radius:6px;overflow-x:auto;font-size:13px}
.header{display:flex;align-items:center;gap:10px;margin-bottom:20px;padding-bottom:12px;border-bottom:2px solid #D4AF37}
.logo{width:28px;height:28px;border-radius:50%;background:linear-gradient(135deg,#D4AF37,#8B5CF6);display:flex;align-items:center;justify-content:center;color:#fff;font-weight:bold;font-size:12px}
.footer{margin-top:30px;padding-top:12px;border-top:1px solid #ddd;font-size:11px;color:#888}
</style></head><body>
<div class="header"><div class="logo">M</div><div><strong>MAX AI Assistant</strong><br><span style="font-size:12px;color:#888">${new Date().toLocaleString()}</span></div></div>
${markdownToHtml(content)}
<div class="footer">Generated by MAX AI — Empire Management System</div>
</body></html>`);
    doc.close();
    setTimeout(() => {
      iframe.contentWindow?.print();
      setTimeout(() => document.body.removeChild(iframe), 1000);
    }, 300);
    showStatus('Print dialog opened — Save as PDF');
  };

  const sendTelegram = async () => {
    setOpen(false);
    showStatus('Sending...');
    try {
      // Strip markdown formatting for clean Telegram message
      const plain = content
        .replace(/```[\s\S]*?```/g, (m) => m) // keep code blocks
        .replace(/#{1,6}\s/g, '')              // remove heading markers
        .trim();
      const resp = await fetch(API_URL + '/max/telegram/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: plain.slice(0, 4000) }),
      });
      if (resp.ok) {
        showStatus('Sent to Telegram');
      } else {
        const data = await resp.json().catch(() => ({}));
        showStatus(data.detail || 'Telegram not configured');
      }
    } catch {
      showStatus('Send failed');
    }
  };

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-1 text-xs px-2 py-1 rounded transition-colors"
        style={{
          background: open ? 'rgba(212,175,55,0.15)' : 'var(--elevated)',
          color: open ? 'var(--gold)' : 'var(--text-secondary)',
          border: `1px solid ${open ? 'var(--gold-border)' : 'var(--border)'}`,
        }}
        title="Share / Export"
      >
        <Share2 className="w-3 h-3" />Share
      </button>
      {status && (
        <span className="absolute -top-7 left-0 text-xs px-2 py-0.5 rounded whitespace-nowrap"
          style={{ background: 'var(--surface)', color: 'var(--gold)', border: '1px solid var(--gold-border)' }}>
          {status}
        </span>
      )}
      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
          <div className="absolute bottom-full left-0 mb-1 z-50 py-1 rounded-lg shadow-lg min-w-[160px]"
            style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}>
            <button onClick={copyFull} className="w-full flex items-center gap-2 px-3 py-2 text-xs hover:opacity-80 transition-opacity text-left"
              style={{ color: 'var(--text-primary)' }}>
              <Copy className="w-3.5 h-3.5" style={{ color: 'var(--text-secondary)' }} />Copy Full Response
            </button>
            <button onClick={printMessage} className="w-full flex items-center gap-2 px-3 py-2 text-xs hover:opacity-80 transition-opacity text-left"
              style={{ color: 'var(--text-primary)' }}>
              <Printer className="w-3.5 h-3.5" style={{ color: 'var(--text-secondary)' }} />Print
            </button>
            <button onClick={exportPdf} className="w-full flex items-center gap-2 px-3 py-2 text-xs hover:opacity-80 transition-opacity text-left"
              style={{ color: 'var(--text-primary)' }}>
              <FileDown className="w-3.5 h-3.5" style={{ color: 'var(--text-secondary)' }} />Save as PDF
            </button>
            <div style={{ borderTop: '1px solid var(--border)', margin: '2px 0' }} />
            <button onClick={sendTelegram} className="w-full flex items-center gap-2 px-3 py-2 text-xs hover:opacity-80 transition-opacity text-left"
              style={{ color: 'var(--text-primary)' }}>
              <Send className="w-3.5 h-3.5" style={{ color: 'var(--text-secondary)' }} />Send to Telegram
            </button>
          </div>
        </>
      )}
    </div>
  );
}

/** Simple markdown → HTML converter for print/PDF */
function markdownToHtml(md: string): string {
  return md
    // Code blocks
    .replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code>$2</code></pre>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code style="background:#f0f0f0;padding:2px 4px;border-radius:3px;font-size:13px">$1</code>')
    // Bold
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    // Italic
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')
    // Headers
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Tables
    .replace(/^\|(.+)\|$/gm, (_, row) => {
      const cells = row.split('|').map((c: string) => c.trim());
      return '<tr>' + cells.map((c: string) => `<td>${c}</td>`).join('') + '</tr>';
    })
    .replace(/(<tr>.*<\/tr>\n?)+/g, (m) => {
      // Convert first row to th
      const first = m.replace(/<\/?tr>/g, '').split('\n')[0] || '';
      return '<table>' + m + '</table>';
    })
    // Remove table separator rows
    .replace(/<tr><td>[-:| ]+<\/td>.*?<\/tr>/g, '')
    // Unordered lists
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => '<ul>' + m + '</ul>')
    // Paragraphs (double newline)
    .replace(/\n\n/g, '</p><p>')
    // Single newlines in flow
    .replace(/\n/g, '<br>')
    // Wrap in paragraph
    .replace(/^/, '<p>')
    .replace(/$/, '</p>');
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000); }}
      className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-1 text-xs px-2 py-1 rounded"
      style={{ background: 'var(--elevated)', color: copied ? '#22c55e' : 'var(--text-secondary)', border: '1px solid var(--border)' }}
    >
      {copied ? <><Check className="w-3 h-3" />Copied</> : <><Copy className="w-3 h-3" />Copy</>}
    </button>
  );
}

function PlayButton({ text }: { text: string }) {
  const [state, setState] = useState<'idle' | 'loading' | 'playing'>('idle');
  const audioRef = useRef<HTMLAudioElement | null>(null);

  const stop = useCallback(() => {
    if (audioRef.current) {
      audioRef.current.pause();
      audioRef.current.currentTime = 0;
      URL.revokeObjectURL(audioRef.current.src);
      audioRef.current = null;
    }
    setState('idle');
  }, []);

  const play = useCallback(async () => {
    if (state === 'playing') { stop(); return; }

    // Strip markdown for cleaner speech
    const plain = text
      .replace(/```[\s\S]*?```/g, '')          // remove code blocks
      .replace(/`[^`]+`/g, '')                 // remove inline code
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // links → text only
      .replace(/[#*_~>|]/g, '')                // remove markdown chars
      .replace(/\n{2,}/g, '. ')                // paragraph breaks → periods
      .replace(/\n/g, ' ')                     // newlines → spaces
      .trim();

    if (!plain) return;

    setState('loading');
    try {
      const resp = await fetch(API_URL + '/max/tts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: plain }),
      });

      if (!resp.ok) { setState('idle'); return; }

      const blob = await resp.blob();
      const url = URL.createObjectURL(blob);
      const audio = new Audio(url);
      audioRef.current = audio;

      audio.onplay = () => setState('playing');
      audio.onended = () => { URL.revokeObjectURL(url); audioRef.current = null; setState('idle'); };
      audio.onerror = () => { URL.revokeObjectURL(url); audioRef.current = null; setState('idle'); };

      await audio.play();
    } catch {
      setState('idle');
    }
  }, [text, state, stop]);

  const icon = state === 'loading'
    ? <Loader2 className="w-3 h-3 animate-spin" />
    : state === 'playing'
      ? <Square className="w-3 h-3" />
      : <Volume2 className="w-3 h-3" />;

  const label = state === 'loading' ? 'Loading...' : state === 'playing' ? 'Stop' : 'Listen';

  return (
    <button
      onClick={play}
      className="flex items-center gap-1 text-xs px-2 py-1 rounded transition-colors"
      style={{
        background: state === 'playing' ? 'rgba(212,175,55,0.15)' : 'var(--elevated)',
        color: state === 'playing' ? 'var(--gold)' : 'var(--text-secondary)',
        border: `1px solid ${state === 'playing' ? 'var(--gold-border)' : 'var(--border)'}`,
      }}
      title={state === 'playing' ? 'Stop playback' : 'Listen to MAX'}
    >
      {icon}{label}
    </button>
  );
}

export default function MessageBubble({ message }: { message: Message }) {
  const isUser = message.role === 'user';

  return (
    <div className={'msg-in flex ' + (isUser ? 'justify-end' : 'justify-start')}>
      {isUser ? (
        /* ── user bubble ───────────────────────────────────── */
        <div
          className="max-w-[78%] rounded-2xl rounded-br-sm px-4 py-3"
          style={{
            background: 'linear-gradient(135deg, #C9A025 0%, #D4AF37 60%, #B8962E 100%)',
            color: '#0a0a0a',
          }}
        >
          {message.image && (
            <p className="text-xs mb-2 opacity-60 flex items-center gap-1">📎 {message.image}</p>
          )}
          <p className="whitespace-pre-wrap text-sm leading-relaxed font-medium">{message.content}</p>
        </div>
      ) : (
        /* ── assistant bubble ─────────────────────────────── */
        <div className="max-w-[85%] flex gap-3 items-start">
          {/* MAX avatar beside bubble */}
          <div
            className="w-9 h-9 rounded-full flex items-center justify-center shrink-0 mt-0.5 max-avatar-glow"
            style={{
              background: 'linear-gradient(135deg, #D4AF37 0%, #8B5CF6 100%)',
              border: '2px solid var(--gold)',
            }}
          >
            <Brain className="w-4 h-4 text-white" />
          </div>
        <div
          className="flex-1 rounded-2xl rounded-tl-sm px-4 py-3"
          style={{
            background: 'var(--surface)',
            border: '1px solid var(--border)',
          }}
        >
          {message.image && (
            <p className="text-xs mb-2 flex items-center gap-1" style={{ color: 'var(--text-muted)' }}>📎 {message.image}</p>
          )}
          <div className="chat-markdown">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                code({ className, children }) {
                  const match = /language-(\w+)/.exec(className || '');
                  const str   = String(children).replace(/\n$/, '');
                  const block = match || str.includes('\n');
                  return block ? (
                    <div className="relative group my-3">
                      <CopyButton text={str} />
                      <SyntaxHighlighter
                        style={oneDark}
                        language={match?.[1] || 'text'}
                        PreTag="div"
                        customStyle={{
                          background: '#0d0d1f',
                          borderRadius: '8px',
                          fontSize: '12.5px',
                          margin: 0,
                          border: '1px solid rgba(139,92,246,0.2)',
                        }}
                      >
                        {str}
                      </SyntaxHighlighter>
                    </div>
                  ) : (
                    <code
                      className="px-1.5 py-0.5 rounded text-xs font-mono"
                      style={{ background: 'var(--purple-pale)', color: '#c4b0ff', border: '1px solid var(--purple-border)' }}
                    >
                      {children}
                    </code>
                  );
                },
                table({ children }) {
                  return <div className="overflow-x-auto my-2"><table className="border-collapse w-full text-sm">{children}</table></div>;
                },
                th({ children }) {
                  return <th style={{ background: 'var(--elevated)', color: 'var(--gold)', borderColor: 'var(--border)' }} className="border px-3 py-1.5 text-left font-semibold">{children}</th>;
                },
                td({ children }) {
                  return <td style={{ borderColor: 'var(--border)' }} className="border px-3 py-1.5">{children}</td>;
                },
                a({ href, children }) {
                  return <a href={href} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--purple)' }} className="underline hover:opacity-80">{children}</a>;
                },
              }}
            >
              {message.content}
            </ReactMarkdown>
          </div>
          {message.toolResults?.map((tr, i) => (
            <ToolResultCard key={i} result={tr} />
          ))}
          <div className="flex items-center gap-2 mt-2">
            <PlayButton text={message.content} />
            <ShareMenu content={message.content} toolResults={message.toolResults} />
            {message.model && (
              <span className="text-xs font-mono" style={{ color: 'var(--text-muted)' }}>via {message.model}</span>
            )}
          </div>
        </div>
        </div>
      )}
    </div>
  );
}
