import { Listing, PlatformConnection, RelistSchedule, DashboardStats, PricingComp } from './types';

export const mockStats: DashboardStats = {
  total_listings: 147,
  active_listings: 89,
  sold_this_month: 23,
  revenue_this_month: 4287.50,
  avg_days_to_sell: 8.3,
  total_platforms: 3,
  pending_crossposts: 14,
  total_value: 12450.00,
};

export const mockListings: Listing[] = [
  {
    id: 'LST-001',
    title: 'Vintage Levi\'s 501 Jeans - 32x30 Dark Wash',
    description: 'Classic vintage Levi\'s 501 button fly jeans. Dark wash, minimal fading. Made in USA tag. Great condition with no holes or stains. Waist 32, inseam 30.',
    price: 68.00,
    purchase_price: 12.00,
    category: 'Clothing',
    condition: 'good',
    photos: ['/placeholder-jeans.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', listing_id: 'EB-294851', url: 'https://ebay.com/itm/294851', status: 'listed', listed_at: '2026-02-28', price: 68.00 },
      { platform: 'etsy', listing_id: 'ET-182734', url: 'https://etsy.com/listing/182734', status: 'listed', listed_at: '2026-03-01', price: 72.00 },
    ],
    tags: ['vintage', 'levis', 'denim', '501', 'made-in-usa'],
    sku: 'VTG-LEV-001',
    quantity: 1,
    weight_oz: 28,
    created_at: '2026-02-27',
    updated_at: '2026-03-01',
    views: 234,
    favorites: 18,
  },
  {
    id: 'LST-002',
    title: 'Nintendo Switch OLED - White, Complete in Box',
    description: 'Nintendo Switch OLED model in white. Includes dock, joy-cons, grip, HDMI cable, and charger. Original box. Screen in perfect condition, no scratches. Adult owned.',
    price: 285.00,
    purchase_price: 180.00,
    category: 'Electronics',
    condition: 'like_new',
    photos: ['/placeholder-switch.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', listing_id: 'EB-294852', url: 'https://ebay.com/itm/294852', status: 'listed', listed_at: '2026-03-02', price: 285.00 },
      { platform: 'facebook', status: 'listed', listed_at: '2026-03-02', price: 275.00 },
    ],
    tags: ['nintendo', 'switch', 'oled', 'gaming', 'console'],
    sku: 'ELEC-NSW-002',
    quantity: 1,
    weight_oz: 48,
    created_at: '2026-03-01',
    views: 456,
    favorites: 32,
  },
  {
    id: 'LST-003',
    title: 'Patagonia Better Sweater Fleece - Men\'s L Navy',
    description: 'Patagonia Better Sweater full-zip fleece jacket. Men\'s size Large. Navy blue. Excellent condition, barely worn. All zippers work perfectly.',
    price: 89.00,
    purchase_price: 22.00,
    category: 'Clothing',
    condition: 'like_new',
    photos: ['/placeholder-fleece.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', listing_id: 'EB-294853', status: 'listed', listed_at: '2026-02-25', price: 89.00 },
      { platform: 'etsy', status: 'pending', price: 95.00 },
      { platform: 'mercari', status: 'listed', listed_at: '2026-02-26', price: 85.00 },
    ],
    tags: ['patagonia', 'fleece', 'better-sweater', 'outdoor'],
    sku: 'CLT-PAT-003',
    quantity: 1,
    weight_oz: 18,
    created_at: '2026-02-24',
    views: 189,
    favorites: 14,
  },
  {
    id: 'LST-004',
    title: 'Vintage Pyrex Primary Colors Mixing Bowl Set',
    description: 'Complete set of 4 vintage Pyrex primary colors nesting mixing bowls (#401-404). Yellow, green, red, blue. No chips or cracks. Minor wear consistent with age.',
    price: 145.00,
    purchase_price: 35.00,
    category: 'Collectibles',
    condition: 'good',
    photos: ['/placeholder-pyrex.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', listing_id: 'EB-294854', status: 'listed', listed_at: '2026-02-20', price: 145.00 },
      { platform: 'etsy', listing_id: 'ET-182735', status: 'listed', listed_at: '2026-02-21', price: 155.00 },
    ],
    tags: ['pyrex', 'vintage', 'primary-colors', 'mixing-bowls', 'kitchen'],
    sku: 'COL-PYR-004',
    quantity: 1,
    weight_oz: 96,
    created_at: '2026-02-19',
    views: 567,
    favorites: 45,
  },
  {
    id: 'LST-005',
    title: 'Sony WH-1000XM5 Headphones - Black',
    description: 'Sony WH-1000XM5 wireless noise-cancelling headphones. Black colorway. Includes carrying case, USB-C cable, and audio cable. Battery life still excellent.',
    price: 195.00,
    purchase_price: 120.00,
    category: 'Electronics',
    condition: 'like_new',
    photos: ['/placeholder-headphones.jpg'],
    status: 'sold',
    platforms: [
      { platform: 'ebay', listing_id: 'EB-294855', status: 'sold', listed_at: '2026-02-15', price: 195.00 },
    ],
    tags: ['sony', 'headphones', 'noise-cancelling', 'wireless'],
    sku: 'ELEC-SNY-005',
    quantity: 0,
    weight_oz: 14,
    created_at: '2026-02-14',
    sold_at: '2026-03-05',
    sold_price: 190.00,
    sold_platform: 'ebay',
    views: 312,
    favorites: 28,
  },
  {
    id: 'LST-006',
    title: 'The North Face Nuptse 700 Puffer - Women\'s M',
    description: 'The North Face 1996 Retro Nuptse jacket, women\'s medium. Black. 700-fill goose down. Excellent condition. No rips, tears, or stains. Packs down small.',
    price: 175.00,
    purchase_price: 45.00,
    category: 'Clothing',
    condition: 'good',
    photos: ['/placeholder-nuptse.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', status: 'listed', listed_at: '2026-03-04', price: 175.00 },
      { platform: 'poshmark', status: 'listed', listed_at: '2026-03-04', price: 170.00 },
    ],
    tags: ['north-face', 'nuptse', 'puffer', 'jacket', 'winter'],
    sku: 'CLT-TNF-006',
    quantity: 1,
    weight_oz: 22,
    created_at: '2026-03-03',
    views: 98,
    favorites: 11,
  },
  {
    id: 'LST-007',
    title: 'Apple AirPods Pro 2nd Gen - USB-C w/ Case',
    description: 'Apple AirPods Pro 2nd generation with USB-C MagSafe charging case. Both earbuds and case in great condition. Active noise cancellation works perfectly. Includes original box.',
    price: 155.00,
    purchase_price: 90.00,
    category: 'Electronics',
    condition: 'good',
    photos: ['/placeholder-airpods.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', status: 'listed', listed_at: '2026-03-06', price: 155.00 },
      { platform: 'facebook', status: 'listed', listed_at: '2026-03-06', price: 145.00 },
      { platform: 'mercari', status: 'error', error: 'Category mismatch - needs review' },
    ],
    tags: ['apple', 'airpods', 'pro', 'wireless', 'earbuds'],
    sku: 'ELEC-APL-007',
    quantity: 1,
    weight_oz: 6,
    created_at: '2026-03-05',
    views: 78,
    favorites: 9,
  },
  {
    id: 'LST-008',
    title: 'Vintage Carhartt Detroit Jacket - XL Tan',
    description: 'Vintage Carhartt Detroit jacket, blanket lined. Size XL. Tan/duck brown. Classic J001 style. Broken-in perfectly with beautiful patina. No major flaws.',
    price: 125.00,
    purchase_price: 30.00,
    category: 'Clothing',
    condition: 'good',
    photos: ['/placeholder-carhartt.jpg'],
    status: 'sold',
    platforms: [
      { platform: 'ebay', status: 'sold', listed_at: '2026-02-10', price: 125.00 },
      { platform: 'etsy', status: 'delisted', listed_at: '2026-02-11' },
    ],
    tags: ['carhartt', 'vintage', 'detroit-jacket', 'workwear'],
    sku: 'CLT-CRH-008',
    quantity: 0,
    weight_oz: 40,
    created_at: '2026-02-09',
    sold_at: '2026-03-02',
    sold_price: 119.99,
    sold_platform: 'ebay',
    views: 445,
    favorites: 37,
  },
  {
    id: 'LST-009',
    title: 'KitchenAid Artisan Stand Mixer 5qt - Empire Red',
    description: 'KitchenAid Artisan series tilt-head stand mixer. 5-quart capacity. Empire Red color. Includes flat beater, dough hook, wire whip, and pouring shield. Works perfectly.',
    price: 215.00,
    purchase_price: 75.00,
    category: 'Home',
    condition: 'good',
    photos: ['/placeholder-mixer.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', status: 'listed', listed_at: '2026-03-01', price: 215.00 },
      { platform: 'facebook', status: 'listed', listed_at: '2026-03-02', price: 200.00 },
    ],
    tags: ['kitchenaid', 'mixer', 'stand-mixer', 'kitchen', 'appliance'],
    sku: 'HOM-KAD-009',
    quantity: 1,
    weight_oz: 384,
    created_at: '2026-02-28',
    views: 167,
    favorites: 21,
  },
  {
    id: 'LST-010',
    title: 'First Edition Harry Potter and the Sorcerer\'s Stone',
    description: 'First American edition, later printing of Harry Potter and the Sorcerer\'s Stone by J.K. Rowling. Scholastic, 1998. Hardcover with dust jacket. Very good condition.',
    price: 85.00,
    purchase_price: 8.00,
    category: 'Books',
    condition: 'good',
    photos: ['/placeholder-book.jpg'],
    status: 'draft',
    platforms: [],
    tags: ['harry-potter', 'first-edition', 'books', 'collectible'],
    sku: 'BOK-HP-010',
    quantity: 1,
    weight_oz: 16,
    created_at: '2026-03-07',
    views: 0,
    favorites: 0,
  },
  {
    id: 'LST-011',
    title: 'Nike Dunk Low Panda - Size 10.5 DS',
    description: 'Nike Dunk Low Retro "Panda" Black White. Men\'s size 10.5. Deadstock, never worn. Includes original box and extra laces. 100% authentic, purchased from Nike.com.',
    price: 115.00,
    purchase_price: 110.00,
    category: 'Clothing',
    condition: 'new',
    photos: ['/placeholder-dunks.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', status: 'listed', listed_at: '2026-03-07', price: 115.00 },
      { platform: 'shopify', status: 'listed', listed_at: '2026-03-07', price: 120.00 },
    ],
    tags: ['nike', 'dunk', 'panda', 'sneakers', 'deadstock'],
    sku: 'CLT-NKE-011',
    quantity: 1,
    weight_oz: 32,
    created_at: '2026-03-06',
    views: 52,
    favorites: 7,
  },
  {
    id: 'LST-012',
    title: 'Dyson V11 Torque Drive Cordless Vacuum',
    description: 'Dyson V11 Torque Drive cordless stick vacuum. Includes torque drive head, soft roller head, mini motorized tool, combination tool, and crevice tool. Wall mount bracket included. Battery holds full charge.',
    price: 299.00,
    purchase_price: 150.00,
    category: 'Home',
    condition: 'like_new',
    photos: ['/placeholder-dyson.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', status: 'listed', listed_at: '2026-03-03', price: 299.00 },
      { platform: 'facebook', status: 'pending' },
    ],
    tags: ['dyson', 'vacuum', 'cordless', 'v11', 'home'],
    sku: 'HOM-DYS-012',
    quantity: 1,
    weight_oz: 108,
    created_at: '2026-03-02',
    views: 203,
    favorites: 15,
  },
  {
    id: 'LST-013',
    title: 'Vintage Starter Jacket - Chicago Bulls XL',
    description: 'Vintage 90s Starter pullover jacket, Chicago Bulls. Size XL. Classic half-zip with kangaroo pocket. Red/black colorway. Great vintage condition.',
    price: 95.00,
    purchase_price: 18.00,
    category: 'Clothing',
    condition: 'good',
    photos: ['/placeholder-starter.jpg'],
    status: 'sold',
    platforms: [
      { platform: 'ebay', status: 'sold', listed_at: '2026-02-18', price: 95.00 },
    ],
    tags: ['vintage', 'starter', 'bulls', 'chicago', '90s'],
    sku: 'CLT-STR-013',
    quantity: 0,
    created_at: '2026-02-17',
    sold_at: '2026-03-08',
    sold_price: 92.00,
    sold_platform: 'ebay',
    views: 289,
    favorites: 22,
  },
  {
    id: 'LST-014',
    title: 'LEGO Star Wars Millennium Falcon 75375 - Sealed',
    description: 'LEGO Star Wars Millennium Falcon set #75375. Brand new, factory sealed. 921 pieces. Ages 10+. Makes a great gift or collectible.',
    price: 169.99,
    purchase_price: 119.99,
    category: 'Toys',
    condition: 'new',
    photos: ['/placeholder-lego.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', status: 'listed', listed_at: '2026-03-05', price: 169.99 },
      { platform: 'amazon', status: 'pending' },
    ],
    tags: ['lego', 'star-wars', 'millennium-falcon', 'sealed', 'collectible'],
    sku: 'TOY-LEG-014',
    quantity: 2,
    weight_oz: 64,
    created_at: '2026-03-04',
    views: 134,
    favorites: 19,
  },
  {
    id: 'LST-015',
    title: 'Garmin Fenix 7S Solar - Slate Gray',
    description: 'Garmin Fenix 7S Solar multisport GPS watch. Slate gray with black silicone band. Solar charging lens. All sensors working. Includes charger. Minor desk diving marks.',
    price: 345.00,
    purchase_price: 200.00,
    category: 'Electronics',
    condition: 'good',
    photos: ['/placeholder-garmin.jpg'],
    status: 'active',
    platforms: [
      { platform: 'ebay', status: 'listed', listed_at: '2026-03-08', price: 345.00 },
    ],
    tags: ['garmin', 'fenix', 'smartwatch', 'gps', 'solar'],
    sku: 'ELEC-GAR-015',
    quantity: 1,
    weight_oz: 4,
    created_at: '2026-03-07',
    views: 23,
    favorites: 3,
  },
];

export const mockConnections: PlatformConnection[] = [
  {
    platform: 'ebay',
    account_name: 'empire_resells',
    status: 'active',
    listings_count: 67,
    last_sync: '2026-03-09T08:30:00Z',
    connected_at: '2025-11-15',
  },
  {
    platform: 'etsy',
    account_name: 'EmpireVintageGoods',
    status: 'active',
    listings_count: 24,
    last_sync: '2026-03-09T07:45:00Z',
    connected_at: '2025-12-01',
  },
  {
    platform: 'shopify',
    account_name: 'empirebox.myshopify.com',
    status: 'active',
    listings_count: 18,
    last_sync: '2026-03-09T06:00:00Z',
    connected_at: '2026-01-10',
  },
  {
    platform: 'facebook',
    account_name: 'Empire Marketplace',
    status: 'active',
    listings_count: 15,
    last_sync: '2026-03-08T22:00:00Z',
    connected_at: '2026-02-01',
  },
  {
    platform: 'mercari',
    account_name: 'EmpireResells',
    status: 'disconnected',
    listings_count: 8,
    connected_at: '2026-01-20',
  },
  {
    platform: 'poshmark',
    account_name: '',
    status: 'disconnected',
    listings_count: 0,
    connected_at: '',
  },
  {
    platform: 'amazon',
    account_name: '',
    status: 'disconnected',
    listings_count: 0,
    connected_at: '',
  },
  {
    platform: 'depop',
    account_name: '',
    status: 'disconnected',
    listings_count: 0,
    connected_at: '',
  },
];

export const mockSchedules: RelistSchedule[] = [
  {
    id: 'SCH-001',
    listing_id: 'LST-001',
    listing_title: 'Vintage Levi\'s 501 Jeans - 32x30 Dark Wash',
    platforms: ['ebay', 'etsy'],
    frequency: 'weekly',
    next_run: '2026-03-14T09:00:00Z',
    enabled: true,
  },
  {
    id: 'SCH-002',
    listing_id: 'LST-004',
    listing_title: 'Vintage Pyrex Primary Colors Mixing Bowl Set',
    platforms: ['ebay', 'etsy'],
    frequency: 'biweekly',
    next_run: '2026-03-19T09:00:00Z',
    enabled: true,
  },
  {
    id: 'SCH-003',
    listing_id: 'LST-006',
    listing_title: 'The North Face Nuptse 700 Puffer - Women\'s M',
    platforms: ['ebay', 'poshmark'],
    frequency: 'weekly',
    next_run: '2026-03-11T09:00:00Z',
    enabled: true,
  },
  {
    id: 'SCH-004',
    listing_id: 'LST-009',
    listing_title: 'KitchenAid Artisan Stand Mixer 5qt - Empire Red',
    platforms: ['ebay', 'facebook'],
    frequency: 'monthly',
    next_run: '2026-04-01T09:00:00Z',
    enabled: false,
  },
  {
    id: 'SCH-005',
    listing_id: 'LST-012',
    listing_title: 'Dyson V11 Torque Drive Cordless Vacuum',
    platforms: ['ebay'],
    frequency: 'daily',
    next_run: '2026-03-10T09:00:00Z',
    enabled: true,
  },
];

export const mockComps: PricingComp[] = [
  { title: 'Vintage Levi 501 Jeans 32x30 Dark', platform: 'ebay', sold_price: 72.00, sold_date: '2026-03-05', condition: 'Good' },
  { title: 'Levis 501 Original Fit 32 30 Dark Wash', platform: 'ebay', sold_price: 58.99, sold_date: '2026-03-03', condition: 'Good' },
  { title: 'Vintage 501 Levi Jeans Made in USA 32', platform: 'etsy', sold_price: 85.00, sold_date: '2026-03-01', condition: 'Like New' },
  { title: 'Levi\'s 501 Button Fly Jeans Vintage 32x30', platform: 'ebay', sold_price: 64.50, sold_date: '2026-02-28', condition: 'Good' },
  { title: 'Vintage Levis 501 Dark Indigo Wash', platform: 'mercari', sold_price: 55.00, sold_date: '2026-02-25', condition: 'Fair' },
  { title: '90s Levi\'s 501 Jeans 32 x 30 USA Made', platform: 'ebay', sold_price: 79.99, sold_date: '2026-02-22', condition: 'Like New' },
];

export const mockActivities = [
  { id: 1, action: 'listed', listing: 'Garmin Fenix 7S Solar', platform: 'ebay', time: '2 hours ago' },
  { id: 2, action: 'sold', listing: 'Vintage Starter Jacket - Chicago Bulls', platform: 'ebay', time: '5 hours ago', amount: 92.00 },
  { id: 3, action: 'crossposted', listing: 'Nike Dunk Low Panda', platform: 'shopify', time: '8 hours ago' },
  { id: 4, action: 'relisted', listing: 'Vintage Pyrex Primary Colors Set', platform: 'etsy', time: '12 hours ago' },
  { id: 5, action: 'listed', listing: 'Apple AirPods Pro 2nd Gen', platform: 'facebook', time: '1 day ago' },
  { id: 6, action: 'sold', listing: 'Sony WH-1000XM5 Headphones', platform: 'ebay', time: '1 day ago', amount: 190.00 },
  { id: 7, action: 'crossposted', listing: 'Dyson V11 Torque Drive', platform: 'facebook', time: '2 days ago' },
  { id: 8, action: 'listed', listing: 'LEGO Star Wars Millennium Falcon', platform: 'ebay', time: '2 days ago' },
  { id: 9, action: 'relisted', listing: 'Vintage Levi\'s 501 Jeans', platform: 'ebay', time: '3 days ago' },
  { id: 10, action: 'sold', listing: 'Vintage Carhartt Detroit Jacket', platform: 'ebay', time: '3 days ago', amount: 119.99 },
];

export const mockRevenueByPlatform = [
  { platform: 'eBay', revenue: 2840, sales: 15 },
  { platform: 'Etsy', revenue: 680, sales: 4 },
  { platform: 'Shopify', revenue: 420, sales: 2 },
  { platform: 'Facebook', revenue: 225, sales: 1 },
  { platform: 'Mercari', revenue: 122, sales: 1 },
];

export const mockSalesTrend = [
  { date: 'Dec 10', revenue: 145, sales: 2 },
  { date: 'Dec 17', revenue: 280, sales: 3 },
  { date: 'Dec 24', revenue: 520, sales: 5 },
  { date: 'Dec 31', revenue: 390, sales: 4 },
  { date: 'Jan 7', revenue: 210, sales: 2 },
  { date: 'Jan 14', revenue: 340, sales: 3 },
  { date: 'Jan 21', revenue: 180, sales: 2 },
  { date: 'Jan 28', revenue: 460, sales: 4 },
  { date: 'Feb 4', revenue: 290, sales: 3 },
  { date: 'Feb 11', revenue: 520, sales: 5 },
  { date: 'Feb 18', revenue: 380, sales: 3 },
  { date: 'Feb 25', revenue: 610, sales: 6 },
  { date: 'Mar 4', revenue: 450, sales: 4 },
];

export const mockStatusBreakdown = [
  { name: 'Active', value: 89, fill: '#16a34a' },
  { name: 'Draft', value: 12, fill: '#9ca3af' },
  { name: 'Sold', value: 38, fill: '#2563eb' },
  { name: 'Archived', value: 8, fill: '#d4d4d4' },
];

export const mockCategoryRevenue = [
  { category: 'Clothing', revenue: 1890 },
  { category: 'Electronics', revenue: 1450 },
  { category: 'Home', revenue: 520 },
  { category: 'Collectibles', revenue: 310 },
  { category: 'Toys', revenue: 170 },
  { category: 'Books', revenue: 85 },
];

export const mockDaysToSellByPlatform = [
  { platform: 'eBay', days: 7.2 },
  { platform: 'Etsy', days: 12.5 },
  { platform: 'Shopify', days: 15.8 },
  { platform: 'Facebook', days: 3.4 },
  { platform: 'Mercari', days: 5.1 },
];

export const PLATFORM_COLORS: Record<string, string> = {
  ebay: '#e53238',
  etsy: '#f1641e',
  shopify: '#96bf48',
  poshmark: '#7f0353',
  mercari: '#4dc4e0',
  amazon: '#ff9900',
  facebook: '#1877f2',
  depop: '#ff2300',
  internal: '#b8960c',
};

export const PLATFORM_FEES: Record<string, { rate: number; fixed: number; label: string }> = {
  ebay: { rate: 0.1325, fixed: 0.30, label: '13.25% + $0.30' },
  etsy: { rate: 0.065, fixed: 0.20, label: '6.5% + $0.20' },
  shopify: { rate: 0.029, fixed: 0.30, label: '2.9% + $0.30' },
  poshmark: { rate: 0.20, fixed: 0, label: '20% flat' },
  mercari: { rate: 0.10, fixed: 0, label: '10% flat' },
  amazon: { rate: 0.15, fixed: 0, label: '15% referral' },
  facebook: { rate: 0.05, fixed: 0, label: '5% (or $0.40 min)' },
  depop: { rate: 0.10, fixed: 0, label: '10% flat' },
};

export const CATEGORIES = ['Clothing', 'Electronics', 'Home', 'Books', 'Toys', 'Sports', 'Collectibles', 'Other'];
export const CONDITIONS: { value: string; label: string }[] = [
  { value: 'new', label: 'New' },
  { value: 'like_new', label: 'Like New' },
  { value: 'good', label: 'Good' },
  { value: 'fair', label: 'Fair' },
  { value: 'poor', label: 'Poor' },
];
