name: market_forge_app

description: A new Flutter project.

publish_to: 'none' # The URL to publish the package.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^5.0.0

flutter:
  uses-material-design: true