"""
RecoveryForge Analysis Schema + Analyzer.

Uses MiniMax vision for image description, tagging, classification,
personal/work routing, and action recommendation.
Runtime truth enforced: success only after provider call completes.
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .minimax_tools import minimax_understand_image
from .recoveryforge_quota import consume_quota, quota_allow_new, check_quota, WINDOW_HOURS

# Analysis result schema keys
CLASSIFICATION_OPTIONS = {"personal", "work_related", "mixed", "unknown"}
BUSINESS_ROUTE_OPTIONS = {
    "empire-workroom", "woodcraft", "archiveforge", "luxeforge",
    "contractorforge", "recoveryforge", "general-business", "unknown-work",
}
ACTION_RECOMMENDATION_OPTIONS = {
    "keep", "archive", "use_for_quote", "add_to_inventory",
    "group_with_similar", "needs_manual_review", "delete_candidate",
    "duplicate_candidate", "customer_project_candidate",
}
QUALITY_THRESHOLD = 6.0  # image_quality_score below this triggers manual review


def _default_analysis_result(image_key: str, error: str) -> dict[str, Any]:
    return {
        "image_key": image_key,
        "analysis_status": "failed",
        "provider": "minimax",
        "transport": "mmx_cli",
        "model": "mmx_vision",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "error": error,
        "stale": False,
        "description": None,
        "tags": ["vision-failed"] if "vision" in error.lower() else [],
        "personal_work_classification": None,
        "business_route": "unknown-work",
        "action_recommendation": "needs_manual_review",
        "image_quality_score": None,
        "analysis_confidence": None,
        "needs_manual_review": True,
        "reason_for_manual_review": error,
    }


async def analyze_image(image_key: str, image_path: str) -> dict[str, Any]:
    """
    Analyze a single image using MiniMax vision.

    Checks quota before proceeding. Returns failed result if cap reached.
    On provider failure, returns failed result without marking image complete
    unless the error indicates the image was actually consumed.

    Returns full analysis result per schema.
    """
    # Check quota
    quota_status = check_quota()
    if not quota_allow_new():
        return _default_analysis_result(
            image_key,
            f"RecoveryForge MCP Understand Image window cap reached "
            f"({quota_status['recoveryforge_window_cap']} analyses per {WINDOW_HOURS}h). "
            f"Window reserve ({quota_status['current_window_reserved_for_general_use']}) preserved for MAX/general use. "
            f"Daily soft cap: {quota_status['recoveryforge_daily_soft_cap']}. "
            f"Next window resets at {quota_status['reset_window_hint']}."
        )

    # Call mmx vision CLI — MiniMax-M2.7 /chat/completions does not support image input
    result = await minimax_understand_image(
        image=image_path,
        prompt="Describe this image in detail. Include: main subject, visible condition, materials/colors/textures, setting/background, any notable defects or damage, and usefulness for business archive, quote, or personal organization. Note any readable text or labels.",
    )

    if not result["success"]:
        consume_quota(image_key, "mmx_vision", success=False, error=result.get("error", "unknown"))
        return _default_analysis_result(image_key, result.get("error", "provider call failed"))

    # Extract description text from mmx CLI response — prefer full_response (untruncated) over summary
    raw = result.get("data", {}).get("full_response") or result.get("data", {}).get("summary", "")

    # If summary is empty/blank, the vision call didn't produce usable content
    if not raw or not raw.strip():
        consume_quota(image_key, "mmx_vision", success=False, error="empty description from mmx vision")
        return _default_analysis_result(image_key, "MiniMax mmx vision returned empty description for this image")

    # Build structured result from mmx vision response
    analysis = _build_structured_analysis(image_key, raw, result.get("data", {}))

    # Mark quota consumed — mmx CLI counts as one provider call
    consume_quota(image_key, "mmx_vision", success=True)

    return analysis


def _build_structured_analysis(image_key: str, description: str, raw_data: dict[str, Any]) -> dict[str, Any]:
    """
    Parse MiniMax raw description into RecoveryForge structured schema.

    Tags are generated by parsing the description text and extracting
    product, material, condition, business unit, urgency, and action keywords.
    """
    desc_lower = description.lower()

    # Generate tags from description keywords
    tags = []
    if any(w in desc_lower for w in ["drapery", "curtain", "blind", "fabric", "upholstery"]):
        tags.append("drapery-fabrics")
    if any(w in desc_lower for w in ["wood", "carpentry", "cabinet", "furniture", "木"]):
        tags.append("wood-craft")
    if any(w in desc_lower for w in ["before", "after", "installation", "install"]):
        tags.append("installation-progress")
    if any(w in desc_lower for w in ["damaged", "stain", "tear", "fade", "worn"]):
        tags.append("damage-noted")
    if any(w in desc_lower for w in ["text", "logo", "label", "sign", "readable"]):
        tags.append("has-text")
    if any(w in desc_lower for w in ["room", "window", "home", "interior"]):
        tags.append("interior")
    if any(w in desc_lower for w in ["workshop", "shop", "garage", "tools"]):
        tags.append("workshop")
    if any(w in desc_lower for w in ["person", "people", "family", "kids"]):
        tags.append("has-people")
    if any(w in desc_lower for w in ["car", "truck", "vehicle"]):
        tags.append("vehicle")
    if any(w in desc_lower for w in ["outdoor", "exterior", "landscape", "garden"]):
        tags.append("outdoor")

    # Personal/work classification (heuristic — MiniMax description drives this)
    personal_indicators = ["family", "personal", "home", "vacation", "kids", "birthday", "holiday"]
    work_indicators = ["installation", "fabric", "woodwork", "workshop", "carpentry", "business", "client"]

    personal_count = sum(1 for w in personal_indicators if w in desc_lower)
    work_count = sum(1 for w in work_indicators if w in desc_lower)

    if personal_count > work_count:
        classification = "personal"
        classification_confidence = min(0.5 + personal_count * 0.15, 0.9)
    elif work_count > personal_count:
        classification = "work_related"
        classification_confidence = min(0.5 + work_count * 0.15, 0.9)
    else:
        classification = "unknown"
        classification_confidence = 0.5

    # Business routing
    if classification == "personal":
        business_route = "general-business"
    elif any(w in desc_lower for w in ["drapery", "curtain", "blind", "fabric", "upholstery"]):
        business_route = "empire-workroom"
    elif any(w in desc_lower for w in ["wood", "cabinet", "carpentry", "furniture"]):
        business_route = "woodcraft"
    elif any(w in desc_lower for w in ["luxury", "designer", "high-end"]):
        business_route = "luxeforge"
    else:
        business_route = "unknown-work"

    # Action recommendation
    if any(w in desc_lower for w in ["damaged", "stain", "tear"]):
        action = "needs_manual_review"
    elif any(w in desc_lower for w in ["before", "installation"]):
        action = "add_to_inventory"
    elif classification == "personal":
        action = "archive"
    else:
        action = "keep"

    # Quality score estimation
    quality_score = 7.0
    if any(w in desc_lower for w in ["damaged", "blur", "dark", "low-res"]):
        quality_score = max(3.0, quality_score - 2)
    elif any(w in desc_lower for w in ["clear", "bright", "high-res", "professional"]):
        quality_score = min(10.0, quality_score + 1)

    needs_manual = quality_score < QUALITY_THRESHOLD or classification == "unknown"

    return {
        "image_key": image_key,
        "analysis_status": "success",
        "provider": "minimax",
        "transport": "mmx_cli",
        "model": "mmx_vision",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "stale": False,
        "description": description,
        "tags": tags,
        "personal_work_classification": {
            "classification": classification,
            "confidence": classification_confidence,
            "reason": f"personal={personal_count}, work={work_count}",
        },
        "business_route": business_route,
        "action_recommendation": action,
        "image_quality_score": quality_score,
        "analysis_confidence": 0.85,
        "needs_manual_review": needs_manual,
        "reason_for_manual_review": "low quality score" if needs_manual else None,
    }