"""Empire house-format pack adapter — CURRENT WIP REFERENCE ONLY.

NOT Max's locked golden. Founder correction 2026-09-25: the shared
reference/empire-house-format generators + samples (incl. B2 flat-fold)
are close current Marleys work for content/numbers, but are NOT the
formatting standard to wire as Max's default.

Use only to regenerate EST-2026-272 current numbers ($15,822.16) or to
inspect WIP layout. True drawing golden is reference/max-golden/ (McLean Whittington).
This pack stays WIP for Marleys EST-2026-272 numbers only.
"""
from __future__ import annotations

import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

logger = logging.getLogger(__name__)

HOUSE_FORMAT_NAME = "empire_house_wip_reference"  # NOT golden / NOT Max default
PACK_DIR = Path(__file__).resolve().parents[4] / "reference" / "empire-house-format"
# parents: estimates -> services -> app -> backend -> repo root? 
# __file__ = .../backend/app/services/estimates/house_format.py
# parents[0]=estimates [1]=services [2]=app [3]=backend [4]=repo ✓
GEN_DIR = PACK_DIR / "generators"
GOLDEN_B2_SHEET = PACK_DIR / "samples" / "GOLDEN_Empire_B2_Sheet_Flat_Fold.pdf"
GOLDEN_ESTIMATE_272 = PACK_DIR / "samples" / "EST-2026-272_Marleys_Banquette.pdf"


def _ensure_gen_path() -> None:
    s = str(GEN_DIR)
    if s not in sys.path:
        sys.path.insert(0, s)


def get_house_build():
    """Import base.build from the house-format pack."""
    _ensure_gen_path()
    import base as house_base  # type: ignore
    return house_base.build


def quote_lines_to_rows(quote: Dict[str, Any]) -> List[tuple]:
    """Map a quotes_v2 quote dict into house-format build() rows.

    Uses line_items as flat DESCRIPTION rows under a single LABOR/MATERIAL
    section split by category when present.
    """
    items = list(quote.get("line_items") or quote.get("items") or [])
    rows: List[tuple] = []
    labor = [it for it in items if "fabric" not in (it.get("category") or "").lower()
             and "fabric" not in (it.get("description") or "").lower()
             and (it.get("unit") or "").lower() != "note"]
    fabric = [it for it in items if it not in labor and (it.get("unit") or "").lower() != "note"]
    notes = [it for it in items if (it.get("unit") or "").lower() == "note"]

    def add_section(title: str, bucket: List[Dict[str, Any]], sub_label: str) -> None:
        if not bucket:
            return
        rows.append(("SEC", title, ""))
        sub = 0.0
        for it in bucket:
            desc = (it.get("description") or "Item").split("\n")[0][:60]
            detail = ""
            parts = (it.get("description") or "").split("\n")
            if len(parts) > 1:
                detail = parts[1][:70]
            src = (it.get("fabric_name") or it.get("category") or "")[:28]
            qty = it.get("quantity")
            rate = it.get("unit_price")
            if rate is None:
                rate = it.get("rate")
            amt = it.get("subtotal")
            if amt is None:
                amt = it.get("amount")
            try:
                amt_f = float(amt or 0)
            except (TypeError, ValueError):
                amt_f = 0.0
            sub += amt_f
            rows.append((desc.upper()[:28], detail, src, qty, rate, amt_f if amt_f else None))
        rows.append(("SUB", round(sub + 1e-9, 2)))

    add_section("LABOR", labor, "labor")
    add_section("MATERIAL", fabric, "material")
    for it in notes:
        rows.append(("SEC", "NOTES", (it.get("description") or "")[:48]))
    return rows


def generate_house_estimate_pdf(
    quote: Dict[str, Any],
    out_path: Optional[str] = None,
) -> bytes:
    """Render a quote with the house portrait estimate builder."""
    build = get_house_build()
    rows = quote_lines_to_rows(quote)
    qn = quote.get("quote_number") or quote.get("id") or "EST"
    title = (quote.get("project_name") or qn).upper()
    sub = (quote.get("project_description") or quote.get("notes") or "")[:140]
    billto = (quote.get("customer_name") or "CLIENT").upper()
    project = (quote.get("customer_address") or "")[:60]
    out = out_path or str(PACK_DIR / "outputs" / f"{qn}.pdf")
    Path(out).parent.mkdir(parents=True, exist_ok=True)

    total = build(
        out,
        "ESTIMATE",
        title,
        sub,
        rows,
        "50% DEPOSIT TO BEGIN · BALANCE ON COMPLETION",
        extra=lambda T: [
            ("DEPOSIT TO BEGIN (50%)", f"${T * 0.5:,.2f}"),
            ("BALANCE ON COMPLETION", f"${T * 0.5:,.2f}"),
        ],
        notes=[
            "DRAFT — not sent. Generated by Max via Empire house format (base.build).",
            f"Quote {qn} · status {(quote.get('status') or 'draft')}.",
        ],
        num=qn,
        brand=("EMPIRE WORKROOM", "CUSTOM UPHOLSTERY & FABRICATION",
               "5124 FROLICH LN · HYATTSVILLE MD 20781"),
        billto=billto,
        project=project or "—",
        foot="EMPIRE WORKROOM · WORKROOM@EMPIREBOX.STORE · (703) 213-6484",
    )
    logger.info("house estimate %s total=%s path=%s", qn, total, out)
    return Path(out).read_bytes()


def regenerate_marleys_272(out_path: Optional[str] = None) -> Path:
    """Run the canonical apex.py generator for EST-2026-272 ($15,822.16)."""
    import subprocess
    env = os.environ.copy()
    env["EMPIRE_HOUSE_FORMAT_OUT"] = str(PACK_DIR / "outputs")
    env["PYTHONPATH"] = str(GEN_DIR) + os.pathsep + env.get("PYTHONPATH", "")
    py = Path(__file__).resolve().parents[3] / "venv" / "bin" / "python"
    if not py.is_file():
        py = Path(sys.executable)
    r = subprocess.run([str(py), "apex.py"], cwd=str(GEN_DIR), env=env, check=True)
    src = PACK_DIR / "outputs" / "EST-2026-272_Marleys_Banquette.pdf"
    if out_path:
        dest = Path(out_path)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(src.read_bytes())
        return dest
    return src
