#!/bin/bash
# CoPilotForge - Context Generator
# Generates fresh context.md with all project info

OUTPUT=~/Empire/products/copilotforge/data/context.md
PROJECTS_DIR=~/Empire

cat > "$OUTPUT" << CONTEXT
# 🔷 CoPilotForge Session Context
Generated: $(date '+%Y-%m-%d %H:%M:%S')

## Active Projects

### Empire App
- **Location:** ~/Empire/empire-app
- **Port:** 3000
- **Tech:** Next.js, TypeScript, Tailwind
- **Features:** MAX AI (audio upload), CRM, Workroom, Inventory, Tasks, Shipping

### AMP (Actitud Mental Positiva)
- **Location:** ~/Projects/actitud-mental-positiva/amp-app
- **Port:** 3002
- **Tech:** Next.js, TypeScript, Tailwind
- **Features:** Meditations, Courses, Events, Checkout/Payments

### Backend (Whisper API)
- **Location:** ~/Empire/backend
- **Port:** 8000
- **Tech:** Python, FastAPI, Whisper

## System Status
CONTEXT

# Add memory info
echo "### Memory" >> "$OUTPUT"
free -h | head -2 >> "$OUTPUT"

# Add running servers
echo "" >> "$OUTPUT"
echo "### Running Servers" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
ss -tlnp 2>/dev/null | grep -E "300[0-9]|8000" | awk '{print $4}' | while read port; do
  echo "- $port"
done >> "$OUTPUT"
echo '```' >> "$OUTPUT"

# Add recent git activity
echo "" >> "$OUTPUT"
echo "### Recent Changes (Empire)" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
cd ~/Empire/empire-app 2>/dev/null && git log --oneline -5 2>/dev/null || echo "No git history"
echo '```' >> "$OUTPUT"

# Add last session notes if exists
if [ -f ~/Empire/products/copilotforge/data/last_session.txt ]; then
  echo "" >> "$OUTPUT"
  echo "### Last Session" >> "$OUTPUT"
  cat ~/Empire/products/copilotforge/data/last_session.txt >> "$OUTPUT"
fi

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "*Context generated by CoPilotForge - Empire Tools*" >> "$OUTPUT"

echo "✅ Context generated: $OUTPUT"
