#!/usr/bin/env python3
"""Generate app/v3/modules.generated.css: the Dark v3 skin for every classic
module page, derived from app/theme/cyber-shell.css.

cyber-shell.css maps the classic screens' hard-coded light palette (Tailwind
arbitrary classes, stock palette classes, inline styles, globals.css vars) onto
the old neon "cyber" palette. This script re-emits every one of those rules
with (a) a stronger selector scoped to Dark v3, and (b) the v3 palette:
graphite #0b0f14 / #121821 surfaces, soft cyan #22d3ee accent, muted coral /
green / amber / blue / violet status colours, no glows, 8-12px radii.
Gold is untouched (gold-docs.generated.css keeps handling it).

Run after gen-cyber-shell.py:  python3 scripts/gen-v3-modules.py
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / 'app'
SRC = ROOT / 'theme' / 'cyber-shell.css'
OUT = ROOT / 'v3' / 'modules.generated.css'
PRE = 'html:not([data-theme="gold"]) .cy-shell.v3'

# rgb family -> (v3 rgb, alpha scale)
FAM = {
    (0, 229, 255): ((34, 211, 238), 0.8),     # cyan accent
    (20, 241, 198): ((95, 199, 154), 1.0),    # teal -> green
    (255, 43, 214): ((240, 138, 122), 1.0),   # magenta -> coral
    (255, 200, 87): ((242, 180, 90), 1.0),    # amber
    (92, 200, 255): ((124, 179, 240), 1.0),   # blue
    (164, 107, 255): ((185, 163, 245), 1.0),  # violet
    (127, 163, 178): ((139, 150, 163), 1.0),  # muted
    (0, 150, 190): ((34, 211, 238), 1.0),
}
# exact surfaces
SURF = {
    'rgba(6,24,36,0.88)': 'rgba(22, 29, 38, 0.78)',
    'rgba(4,18,27,0.92)': 'rgba(18, 24, 33, 0.92)',
    'rgba(3,13,20,0.94)': 'rgba(16, 22, 29, 0.94)',
    'rgba(0,10,16,0.75)': 'rgba(255, 255, 255, 0.04)',
}
HEX = {
    '#00e5ff': '#22d3ee', '#d9f8ff': '#e6edf3', '#7fa3b2': '#8b96a3', '#14f1c6': '#5fc79a',
    '#ff6be3': '#f4a597', '#ff7ae6': '#f4a597', '#ffc857': '#f2b45a', '#a9c7d3': '#c4ced8',
    '#557a8b': '#6b7682', '#5cc8ff': '#7cb3f0', '#b98cff': '#b9a3f5', '#010306': '#0b0f14',
    '#04121b': '#121821', '#bff6ff': '#e6edf3', '#001018': '#06222a',
}


def color(m):
    raw = m.group(0)
    key = raw.replace(' ', '').lower()
    if key in SURF:
        return SURF[key]
    if key.startswith('rgba('):
        r, g, b, a = [float(x) for x in key[5:-1].split(',')]
        fam = FAM.get((int(r), int(g), int(b)))
        if fam:
            (nr, ng, nb), k = fam
            return f'rgba({nr}, {ng}, {nb}, {round(min(1.0, a * k), 3)})'
        return raw
    return HEX.get(key, raw)


def decls(body):
    out = []
    for d in body.split(';'):
        if ':' not in d:
            continue
        prop, val = d.split(':', 1)
        prop = prop.strip()
        imp = '!important' in val
        val = val.replace('!important', '').strip()
        if prop == 'text-shadow':
            val = 'none'
        elif prop == 'box-shadow':
            parts = [p.strip() for p in split_top(val)]
            keep = [p for p in parts if not re.match(r'^(inset\s+)?0\s+0\s+[1-9]\d*px', p)]
            val = ', '.join(keep) if keep else 'none'
        elif prop.startswith('border') and 'radius' in prop:
            val = re.sub(r'\b[1-4]px\b', '8px', val)
            val = re.sub(r'\b[5-6]px\b', '12px', val)
        elif prop == 'background' and 'repeating-linear-gradient' in val:
            val = 'none'
        if prop.startswith('border') and 'radius' not in prop:
            # cyan-tinted hairlines -> neutral v3 hairlines (accent borders >= 0.3 alpha keep the accent)
            val = re.sub(r'rgba\(\s*0,\s*229,\s*255,\s*0?\.[0-2]\d*\s*\)', 'rgba(255, 255, 255, 0.1)', val)
        if prop == 'color':
            # dim body text (#999/#aaa/#ccc...) reads as muted, not faint: >= 4.5:1 on v3 panels
            val = re.sub(r'#557a8b\b', '#8b96a3', val, flags=re.I)
        val = re.sub(r'rgba\([^)]*\)|#[0-9a-fA-F]{3,6}\b', color, val)
        out.append(f'{prop}: {val}{" !important" if imp else ""}')
    return '; '.join(out)


def split_top(s):
    """Split on commas at paren/bracket/quote depth 0."""
    out, cur, depth, q = [], '', 0, None
    for ch in s:
        if q:
            q = None if ch == q else q
        elif ch in '"\'':
            q = ch
        elif ch in '([':
            depth += 1
        elif ch in ')]':
            depth -= 1
        elif ch == ',' and depth == 0:
            out.append(cur); cur = ''; continue
        cur += ch
    out.append(cur)
    return out


def sel(s):
    parts = []
    for p in split_top(s):
        p = p.strip()
        if p.startswith('body:has('):
            return None
        if p.startswith('.cy-shell'):
            p = PRE + p[len('.cy-shell'):]
        else:
            return None
        parts.append(p)
    return ', '.join(parts)


def main():
    css = re.sub(r'/\*.*?\*/', '', SRC.read_text(), flags=re.S)
    lines = ['/* GENERATED by scripts/gen-v3-modules.py from theme/cyber-shell.css — do not edit by hand. */',
             '/* Dark v3 palette for classic module pages. Loaded after the cyber layers, before app-bridge.css. */', '']
    n = 0
    for m in re.finditer(r'([^{}@]+)\{([^{}]*)\}', css):
        s = sel(m.group(1))
        if not s:
            continue
        d = decls(m.group(2))
        if d:
            lines.append(f'{s} {{ {d}; }}')
            n += 1
    OUT.write_text('\n'.join(lines) + '\n')
    print(f'wrote {OUT} ({n} rules)')


if __name__ == '__main__':
    main()
