/**
 * Empire Furniture Catalog — Comprehensive type library
 * 200+ furniture types organized by category.
 * Empire Workroom + WoodCraft can build anything wood & fabric related.
 */

export interface FurnitureType {
  key: string;
  name: string;
  category: 'sofa' | 'chair' | 'ottoman' | 'bench' | 'bed' | 'dining' | 'outdoor' | 'commercial' | 'accent' | 'storage' | 'table' | 'other';
  subcategory?: string;
  measurementPoints: string[];
  fabricSections: string[];
  description?: string;
  /** SVG path hint for generic renderer: 'sofa' | 'chair' | 'armchair' | 'bench' | 'ottoman' | 'bed' | 'stool' | 'table' | 'cabinet' | 'generic' */
  svgHint?: string;
}

export const CATEGORY_LABELS: Record<string, string> = {
  sofa: 'Sofa',
  chair: 'Chair',
  ottoman: 'Ottoman',
  bench: 'Bench',
  bed: 'Bed',
  dining: 'Dining',
  outdoor: 'Outdoor',
  commercial: 'Commercial',
  accent: 'Accent',
  storage: 'Storage',
  table: 'Table',
  other: 'Specialty',
};

export const CATEGORY_ICONS: Record<string, string> = {
  sofa: '🛋️',
  chair: '💺',
  ottoman: '🟫',
  bench: '🪑',
  bed: '🛏️',
  dining: '🍽️',
  outdoor: '☀️',
  commercial: '🏢',
  accent: '✨',
  storage: '🗄️',
  table: '🪵',
  other: '⚡',
};

// ── Standard measurement sets (reusable) ─────────────────────

const SOFA_MEASUREMENTS = [
  'Overall Width', 'Overall Depth', 'Overall Height',
  'Seat Height', 'Seat Depth', 'Arm Height', 'Arm Width',
  'Back Height', 'Cushion Count',
];

const CHAIR_MEASUREMENTS = [
  'Overall Width', 'Overall Depth', 'Overall Height',
  'Seat Width', 'Seat Depth', 'Seat Height', 'Arm Height',
];

const DINING_CHAIR_MEASUREMENTS = [
  'Overall Width', 'Overall Depth', 'Overall Height',
  'Seat Width', 'Seat Depth', 'Back Height Above Seat',
];

const OTTOMAN_MEASUREMENTS = ['Width', 'Depth', 'Height'];

const BENCH_MEASUREMENTS = ['Width', 'Depth', 'Height', 'Leg Style'];

const BED_MEASUREMENTS = [
  'Bed Size', 'Headboard Width', 'Headboard Height',
  'Footboard Height', 'Side Rail Length',
];

const STOOL_MEASUREMENTS = [
  'Seat Width', 'Seat Depth', 'Seat Height',
  'Footrest Height', 'Back Height',
];

// ── Standard fabric section sets ─────────────────────────────

const SOFA_FABRIC = [
  'Seat Cushions', 'Back Cushions', 'Inside Arms', 'Outside Arms',
  'Inside Back', 'Outside Back', 'Arm Fronts', 'Deck',
];

const CHAIR_FABRIC = [
  'Seat Cushion', 'Inside Back', 'Outside Back',
  'Inside Arms (x2)', 'Outside Arms (x2)', 'Arm Fronts (x2)', 'Deck',
];

const ARMLESS_CHAIR_FABRIC = [
  'Seat', 'Inside Back', 'Outside Back', 'Sides (x2)',
];

const OTTOMAN_FABRIC = [
  'Top', 'Front Side', 'Back Side', 'Left Side', 'Right Side',
];

const BENCH_FABRIC = ['Top', 'Front Side', 'Back Side', 'Ends (x2)'];

const HEADBOARD_FABRIC = ['Front Face', 'Top Border', 'Side Borders (x2)', 'Back Panel'];


// ═══════════════════════════════════════════════════════════════
// THE CATALOG — 200+ items
// ═══════════════════════════════════════════════════════════════

export const FURNITURE_TYPES: FurnitureType[] = [

  // ─────────────────────────────────────────────────────────────
  // SOFAS (30+)
  // ─────────────────────────────────────────────────────────────
  { key: 'lawson-sofa', name: 'Lawson Sofa', category: 'sofa', subcategory: 'Classic', svgHint: 'sofa',
    measurementPoints: SOFA_MEASUREMENTS, fabricSections: SOFA_FABRIC,
    description: 'Clean lines, comfortable cushions, slightly reclined back' },
  { key: 'english-roll-arm', name: 'English Roll Arm Sofa', category: 'sofa', subcategory: 'Classic', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Arm Roll Diameter'], fabricSections: SOFA_FABRIC,
    description: 'Signature rolled arms, deep seat, tight back or loose cushions' },
  { key: 'chesterfield-sofa', name: 'Chesterfield Sofa', category: 'sofa', subcategory: 'Classic', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Tufting Depth'], fabricSections: [...SOFA_FABRIC, 'Button Tufting'],
    description: 'Deep button tufting, rolled arms same height as back' },
  { key: 'camelback-sofa', name: 'Camelback Sofa', category: 'sofa', subcategory: 'Traditional', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Camel Hump Height'], fabricSections: SOFA_FABRIC,
    description: 'Arched back with single or double hump, exposed legs' },
  { key: 'cabriole-sofa', name: 'Cabriole Sofa', category: 'sofa', subcategory: 'Traditional', svgHint: 'sofa',
    measurementPoints: SOFA_MEASUREMENTS, fabricSections: SOFA_FABRIC,
    description: 'Continuous curved back flowing into arms' },
  { key: 'bridgewater-sofa', name: 'Bridgewater Sofa', category: 'sofa', subcategory: 'Classic', svgHint: 'sofa',
    measurementPoints: SOFA_MEASUREMENTS, fabricSections: SOFA_FABRIC,
    description: 'Low arms, soft cushions, informal and comfortable' },
  { key: 'tuxedo-sofa', name: 'Tuxedo Sofa', category: 'sofa', subcategory: 'Modern', svgHint: 'sofa',
    measurementPoints: SOFA_MEASUREMENTS, fabricSections: SOFA_FABRIC,
    description: 'Arms and back same height, clean architectural lines' },
  { key: 'mid-century-sofa', name: 'Mid-Century Modern Sofa', category: 'sofa', subcategory: 'Modern', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Leg Height'], fabricSections: SOFA_FABRIC,
    description: 'Clean lines, tapered legs, minimal ornamentation' },
  { key: 'knole-sofa', name: 'Knole Sofa', category: 'sofa', subcategory: 'Traditional', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Side Panel Height'], fabricSections: [...SOFA_FABRIC, 'Side Panels (x2)', 'Finials/Ties'],
    description: 'High sides that fold down, tied with cords/tassels' },
  { key: 'settee', name: 'Settee', category: 'sofa', subcategory: 'Classic', svgHint: 'sofa',
    measurementPoints: SOFA_MEASUREMENTS, fabricSections: SOFA_FABRIC,
    description: 'Small sofa for 2, often with exposed wood frame' },
  { key: 'loveseat', name: 'Loveseat', category: 'sofa', subcategory: 'Classic', svgHint: 'sofa',
    measurementPoints: SOFA_MEASUREMENTS, fabricSections: SOFA_FABRIC,
    description: 'Two-seat sofa, various arm styles' },
  { key: 'daybed-sofa', name: 'Daybed', category: 'sofa', subcategory: 'Specialty', svgHint: 'sofa',
    measurementPoints: ['Overall Width', 'Overall Depth', 'Overall Height', 'Back Height', 'Arm Height', 'Mattress Size'],
    fabricSections: ['Mattress Cover', 'Back Panel', 'Side Arms (x2)', 'Bolsters', 'Deck'],
    description: 'Single bed that doubles as sofa, usually with back and arms' },
  { key: 'sectional-l-shape', name: 'L-Shaped Sectional', category: 'sofa', subcategory: 'Sectional', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Long Side Length', 'Short Side Length', 'Corner Depth'],
    fabricSections: [...SOFA_FABRIC, 'Corner Section', 'Chaise Section'],
    description: 'L-shaped configuration, various arm and cushion styles' },
  { key: 'sectional-u-shape', name: 'U-Shaped Sectional', category: 'sofa', subcategory: 'Sectional', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Total Length', 'Depth at Center'],
    fabricSections: [...SOFA_FABRIC, 'Corner Sections (x2)', 'Center Section'],
    description: 'U-shaped seating for large spaces' },
  { key: 'sectional-curved', name: 'Curved Sectional', category: 'sofa', subcategory: 'Sectional', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Outer Radius', 'Inner Radius', 'Arc Angle'],
    fabricSections: [...SOFA_FABRIC, 'Curved Panels'],
    description: 'Curved/crescent shape, conversation pit style' },
  { key: 'sleeper-sofa', name: 'Sleeper Sofa', category: 'sofa', subcategory: 'Functional', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Mattress Size', 'Open Depth'],
    fabricSections: SOFA_FABRIC,
    description: 'Pull-out bed mechanism inside sofa frame' },
  { key: 'reclining-sofa', name: 'Reclining Sofa', category: 'sofa', subcategory: 'Functional', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Recline Depth', 'Wall Clearance'],
    fabricSections: [...SOFA_FABRIC, 'Footrest'],
    description: 'Built-in recliners in each seat position' },
  { key: 'conversation-sofa', name: 'Conversation Sofa', category: 'sofa', subcategory: 'Specialty', svgHint: 'sofa',
    measurementPoints: [...SOFA_MEASUREMENTS, 'Curve Radius'],
    fabricSections: SOFA_FABRIC,
    description: 'S-shaped or curved for face-to-face seating' },
  { key: 'pit-sofa', name: 'Pit Sofa / Modular', category: 'sofa', subcategory: 'Modern', svgHint: 'sofa',
    measurementPoints: ['Module Width', 'Module Depth', 'Module Height', 'Number of Modules', 'Cushion Count'],
    fabricSections: ['Seat Modules', 'Back Modules', 'Corner Modules', 'Armrest Modules'],
    description: 'Modular pieces that combine into any configuration' },
  { key: 'sofa-bench', name: 'Sofa Bench (Banquette)', category: 'sofa', subcategory: 'Commercial', svgHint: 'sofa',
    measurementPoints: ['Total Length', 'Depth', 'Seat Height', 'Back Height', 'Cushion Count'],
    fabricSections: ['Seat Cushion', 'Back Cushion', 'Side Panels', 'Outside Back'],
    description: 'Long bench seating with back, restaurant/commercial style' },
  { key: 'divan', name: 'Divan', category: 'sofa', subcategory: 'Traditional', svgHint: 'sofa',
    measurementPoints: ['Overall Width', 'Overall Depth', 'Overall Height', 'Arm Height'],
    fabricSections: ['Seat', 'Back', 'Single Arm', 'Bolster'],
    description: 'Backless or single-armed couch, often with bolsters' },
  { key: 'canape', name: 'Canapé', category: 'sofa', subcategory: 'Traditional', svgHint: 'sofa',
    measurementPoints: SOFA_MEASUREMENTS, fabricSections: [...SOFA_FABRIC, 'Exposed Wood Frame'],
    description: 'Small ornate sofa with exposed wood frame' },
  { key: 'recamier', name: 'Récamier', category: 'sofa', subcategory: 'Traditional', svgHint: 'sofa',
    measurementPoints: ['Overall Width', 'Overall Depth', 'Headrest Height', 'Footrest Height'],
    fabricSections: ['Seat', 'Headrest', 'Footrest', 'Outside Body'],
    description: 'Asymmetrical chaise with scrolled headrest and footrest' },
  { key: 'fainting-couch', name: 'Fainting Couch', category: 'sofa', subcategory: 'Traditional', svgHint: 'sofa',
    measurementPoints: ['Overall Width', 'Overall Depth', 'High End Height', 'Low End Height'],
    fabricSections: ['Seat', 'Raised Back', 'Low End', 'Outside Body'],
    description: 'Sloped back, one end higher than other' },

  // ─────────────────────────────────────────────────────────────
  // CHAIRS — Living Room / Lounge (40+)
  // ─────────────────────────────────────────────────────────────
  { key: 'wingback-chair', name: 'Wingback Chair', category: 'chair', subcategory: 'Classic', svgHint: 'armchair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Wing Width', 'Wing Height'],
    fabricSections: ['Seat', 'Inside Back', 'Outside Back', 'Inside Wings (x2)', 'Outside Wings (x2)', 'Inside Arms (x2)', 'Outside Arms (x2)', 'Arm Fronts (x2)', 'Cushion'],
    description: 'High back with side wings, traditional statement piece' },
  { key: 'club-chair', name: 'Club Chair', category: 'chair', subcategory: 'Classic', svgHint: 'armchair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: CHAIR_FABRIC,
    description: 'Deep, low, comfortable — the classic reading chair' },
  { key: 'barrel-chair', name: 'Barrel Chair', category: 'chair', subcategory: 'Modern', svgHint: 'armchair',
    measurementPoints: ['Overall Width (Diameter)', 'Overall Depth', 'Overall Height', 'Seat Height', 'Back Height'],
    fabricSections: ['Seat Cushion', 'Inside Back (curved)', 'Outside Back (curved)', 'Deck'],
    description: 'Rounded wraparound back, swivel or stationary' },
  { key: 'bergere-chair', name: 'Bergère Chair', category: 'chair', subcategory: 'Traditional', svgHint: 'armchair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Exposed Frame Width'], fabricSections: [...CHAIR_FABRIC, 'Exposed Wood Frame'],
    description: 'French armchair with exposed wood frame and upholstered sides' },
  { key: 'fauteuil-chair', name: 'Fauteuil Chair', category: 'chair', subcategory: 'Traditional', svgHint: 'armchair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Back', 'Arm Pads (x2)', 'Exposed Wood Frame'],
    description: 'French open-arm chair with exposed wood' },
  { key: 'slipper-chair', name: 'Slipper Chair', category: 'chair', subcategory: 'Accent', svgHint: 'chair',
    measurementPoints: ['Overall Width', 'Overall Depth', 'Overall Height', 'Seat Height', 'Seat Depth'],
    fabricSections: ['Seat', 'Inside Back', 'Outside Back', 'Sides (x2)'],
    description: 'Armless, low seat height, bedroom or accent piece' },
  { key: 'accent-chair', name: 'Accent Chair', category: 'chair', subcategory: 'Accent', svgHint: 'chair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: CHAIR_FABRIC,
    description: 'General decorative armchair, various styles' },
  { key: 'swivel-chair', name: 'Swivel Chair', category: 'chair', subcategory: 'Modern', svgHint: 'armchair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Swivel Base Diameter'], fabricSections: CHAIR_FABRIC,
    description: 'Rotating base, various upholstery styles' },
  { key: 'tub-chair', name: 'Tub Chair', category: 'chair', subcategory: 'Classic', svgHint: 'armchair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Inside Shell', 'Outside Shell', 'Cushion'],
    description: 'Round continuous back, compact and cozy' },
  { key: 'egg-chair', name: 'Egg Chair', category: 'chair', subcategory: 'Modern', svgHint: 'armchair',
    measurementPoints: ['Overall Width', 'Overall Depth', 'Overall Height', 'Seat Height', 'Shell Diameter'],
    fabricSections: ['Inside Shell', 'Outside Shell', 'Seat Cushion', 'Back Cushion'],
    description: 'Iconic curved shell shape, swivel base' },
  { key: 'papasan-chair', name: 'Papasan Chair', category: 'chair', subcategory: 'Casual', svgHint: 'chair',
    measurementPoints: ['Bowl Diameter', 'Overall Height', 'Seat Height'],
    fabricSections: ['Bowl Cushion', 'Cushion Cover'],
    description: 'Large round bowl on rattan frame with thick cushion' },
  { key: 'recliner', name: 'Recliner', category: 'chair', subcategory: 'Functional', svgHint: 'armchair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Recline Depth', 'Wall Clearance'],
    fabricSections: [...CHAIR_FABRIC, 'Footrest', 'Headrest'],
    description: 'Reclining mechanism, various styles from classic to modern' },
  { key: 'glider-chair', name: 'Glider / Nursery Chair', category: 'chair', subcategory: 'Functional', svgHint: 'armchair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Glide Depth'], fabricSections: CHAIR_FABRIC,
    description: 'Smooth gliding motion, popular for nurseries' },
  { key: 'rocker-chair', name: 'Rocking Chair (Upholstered)', category: 'chair', subcategory: 'Classic', svgHint: 'chair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Rocker Arc Length'], fabricSections: CHAIR_FABRIC,
    description: 'Traditional rocker with full upholstery' },
  { key: 'chaise-lounge', name: 'Chaise Lounge', category: 'chair', subcategory: 'Specialty', svgHint: 'sofa',
    measurementPoints: ['Overall Width', 'Overall Depth', 'Overall Height', 'Arm Height', 'Headrest Height', 'Seat Depth'],
    fabricSections: ['Seat', 'Inside Back', 'Outside Back', 'Inside Arm', 'Outside Arm', 'Headrest', 'Deck'],
    description: 'Long reclining seat with back support' },
  { key: 'lounge-chair', name: 'Lounge Chair', category: 'chair', subcategory: 'Modern', svgHint: 'chair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Back', 'Arms', 'Outside'],
    description: 'Low, relaxed seating, various modern styles' },
  { key: 'peacock-chair', name: 'Peacock Chair (Upholstered)', category: 'chair', subcategory: 'Statement', svgHint: 'chair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Fan Back Height', 'Fan Back Width'],
    fabricSections: ['Seat', 'Fan Back (inside)', 'Fan Back (outside)', 'Arms'],
    description: 'Dramatic fan-shaped back, statement piece' },
  { key: 'throne-chair', name: 'Throne Chair', category: 'chair', subcategory: 'Statement', svgHint: 'armchair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Back Height', 'Crown Height'],
    fabricSections: [...CHAIR_FABRIC, 'Crown/Pediment', 'Exposed Wood/Gold Frame'],
    description: 'Oversized, high-backed, ornate — events and statements' },
  { key: 'gondola-chair', name: 'Gondola Chair', category: 'chair', subcategory: 'Traditional', svgHint: 'armchair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Continuous Back/Arms Shell', 'Outside Shell'],
    description: 'Boat-shaped chair, continuous curved back flowing to arms' },
  { key: 'marquise-chair', name: 'Marquise Chair', category: 'chair', subcategory: 'Traditional', svgHint: 'armchair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: CHAIR_FABRIC,
    description: 'Wide French armchair, like a mini loveseat' },
  { key: 'porter-chair', name: "Porter's Chair", category: 'chair', subcategory: 'Traditional', svgHint: 'armchair',
    measurementPoints: [...CHAIR_MEASUREMENTS, 'Hood Height', 'Hood Depth'],
    fabricSections: ['Seat', 'Inside Back', 'Inside Hood', 'Outside Back/Hood', 'Arms'],
    description: 'Hooded high-back chair, originally for drafty halls' },
  { key: 'channel-back-chair', name: 'Channel Back Chair', category: 'chair', subcategory: 'Modern', svgHint: 'armchair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Channel-Tufted Back', 'Outside Back', 'Arms'],
    description: 'Vertical channel tufting on back, sleek modern look' },
  { key: 'bouclé-chair', name: 'Bouclé Accent Chair', category: 'chair', subcategory: 'Modern', svgHint: 'armchair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: CHAIR_FABRIC,
    description: 'Any shape in textured bouclé fabric, trending modern style' },

  // ─────────────────────────────────────────────────────────────
  // CHAIRS — Dining (25+)
  // ─────────────────────────────────────────────────────────────
  { key: 'parsons-dining-chair', name: 'Parsons Dining Chair', category: 'dining', subcategory: 'Fully Upholstered', svgHint: 'chair',
    measurementPoints: DINING_CHAIR_MEASUREMENTS, fabricSections: ARMLESS_CHAIR_FABRIC,
    description: 'Fully upholstered, straight lines, no exposed frame' },
  { key: 'host-dining-chair', name: 'Host / Captain Chair', category: 'dining', subcategory: 'With Arms', svgHint: 'armchair',
    measurementPoints: [...DINING_CHAIR_MEASUREMENTS, 'Arm Height'], fabricSections: CHAIR_FABRIC,
    description: 'Dining armchair for head of table' },
  { key: 'side-dining-chair', name: 'Side Dining Chair', category: 'dining', subcategory: 'Standard', svgHint: 'chair',
    measurementPoints: DINING_CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Back Panel'],
    description: 'Armless dining chair with upholstered seat and back' },
  { key: 'seat-pad-only', name: 'Seat Pad Only', category: 'dining', subcategory: 'Cushion', svgHint: 'ottoman',
    measurementPoints: ['Width', 'Depth', 'Thickness', 'Shape'],
    fabricSections: ['Top', 'Boxing', 'Bottom'],
    description: 'Drop-in or tie-on seat cushion for existing chair' },
  { key: 'ladder-back-seat', name: 'Ladder Back Chair (Seat Only)', category: 'dining', subcategory: 'Seat Only', svgHint: 'chair',
    measurementPoints: ['Seat Width Front', 'Seat Width Back', 'Seat Depth', 'Frame Style'],
    fabricSections: ['Seat (drop-in or slip)'],
    description: 'Rush or fabric seat replacement for ladder back' },
  { key: 'louis-xvi-dining', name: 'Louis XVI Dining Chair', category: 'dining', subcategory: 'Traditional', svgHint: 'chair',
    measurementPoints: DINING_CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Back (oval/rectangle)', 'Exposed Frame'],
    description: 'French neoclassical with round/oval back and exposed frame' },
  { key: 'shield-back-dining', name: 'Shield Back Dining Chair', category: 'dining', subcategory: 'Traditional', svgHint: 'chair',
    measurementPoints: DINING_CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Shield Back Insert'],
    description: 'Hepplewhite-style shield-shaped back with fabric insert' },
  { key: 'cane-back-dining', name: 'Cane Back Dining Chair (Re-cane)', category: 'dining', subcategory: 'Specialty', svgHint: 'chair',
    measurementPoints: [...DINING_CHAIR_MEASUREMENTS, 'Cane Panel Width', 'Cane Panel Height'],
    fabricSections: ['Seat Cushion', 'Cane Back Panel (press cane or hand-woven)'],
    description: 'Replace or repair cane in back or seat' },
  { key: 'skirted-dining', name: 'Skirted Dining Chair', category: 'dining', subcategory: 'Fully Upholstered', svgHint: 'chair',
    measurementPoints: DINING_CHAIR_MEASUREMENTS, fabricSections: [...ARMLESS_CHAIR_FABRIC, 'Skirt'],
    description: 'Parsons style with decorative skirt at base' },
  { key: 'slipcover-dining', name: 'Slipcover Dining Chair', category: 'dining', subcategory: 'Slipcover', svgHint: 'chair',
    measurementPoints: [...DINING_CHAIR_MEASUREMENTS, 'Leg Height'],
    fabricSections: ['Full Slipcover (removable)'],
    description: 'Removable washable slipcover for dining chairs' },
  { key: 'banquette-straight', name: 'Straight Banquette', category: 'dining', subcategory: 'Banquette', svgHint: 'bench',
    measurementPoints: ['Total Length', 'Depth', 'Seat Height', 'Back Height', 'Sections'],
    fabricSections: ['Seat Cushion', 'Back Cushion', 'Outside Back', 'End Panels'],
    description: 'Straight built-in or freestanding restaurant/kitchen bench' },
  { key: 'banquette-l-shape', name: 'L-Shaped Banquette', category: 'dining', subcategory: 'Banquette', svgHint: 'bench',
    measurementPoints: ['Long Side Length', 'Short Side Length', 'Depth', 'Back Height', 'Corner Style'],
    fabricSections: ['Seat Cushion', 'Back Cushion', 'Corner Section', 'End Panels', 'Outside Back'],
    description: 'L-shaped corner banquette for breakfast nooks' },
  { key: 'banquette-u-shape', name: 'U-Shaped Banquette', category: 'dining', subcategory: 'Banquette', svgHint: 'bench',
    measurementPoints: ['Back Length', 'Side Lengths', 'Depth', 'Back Height'],
    fabricSections: ['Seat Cushion', 'Back Cushion', 'Corner Sections (x2)', 'End Panels', 'Outside Back'],
    description: 'U-shaped booth-style seating' },
  { key: 'banquette-curved', name: 'Curved Banquette', category: 'dining', subcategory: 'Banquette', svgHint: 'bench',
    measurementPoints: ['Outer Radius', 'Inner Radius', 'Arc Angle', 'Back Height'],
    fabricSections: ['Curved Seat', 'Curved Back', 'Outside Back'],
    description: 'Curved/semicircular banquette' },

  // ─────────────────────────────────────────────────────────────
  // OTTOMANS & POUFS (15+)
  // ─────────────────────────────────────────────────────────────
  { key: 'ottoman-square', name: 'Ottoman (Square)', category: 'ottoman', subcategory: 'Standard', svgHint: 'ottoman',
    measurementPoints: OTTOMAN_MEASUREMENTS, fabricSections: [...OTTOMAN_FABRIC, 'Skirt (optional)', 'Tufting (optional)'] },
  { key: 'ottoman-round', name: 'Ottoman (Round)', category: 'ottoman', subcategory: 'Standard', svgHint: 'ottoman',
    measurementPoints: ['Diameter', 'Height'], fabricSections: ['Top', 'Side Band', 'Skirt (optional)'] },
  { key: 'ottoman-rectangular', name: 'Ottoman (Rectangular)', category: 'ottoman', subcategory: 'Standard', svgHint: 'ottoman',
    measurementPoints: OTTOMAN_MEASUREMENTS, fabricSections: OTTOMAN_FABRIC },
  { key: 'cocktail-ottoman', name: 'Cocktail Ottoman', category: 'ottoman', subcategory: 'Large', svgHint: 'ottoman',
    measurementPoints: ['Width', 'Depth', 'Height'], fabricSections: ['Tufted Top', 'Sides', 'Base Rail'],
    description: 'Large tufted ottoman used as coffee table' },
  { key: 'storage-ottoman', name: 'Storage Ottoman', category: 'ottoman', subcategory: 'Functional', svgHint: 'ottoman',
    measurementPoints: [...OTTOMAN_MEASUREMENTS, 'Hinge Type'], fabricSections: [...OTTOMAN_FABRIC, 'Lid Hinge Area'] },
  { key: 'tray-ottoman', name: 'Tray-Top Ottoman', category: 'ottoman', subcategory: 'Functional', svgHint: 'ottoman',
    measurementPoints: OTTOMAN_MEASUREMENTS, fabricSections: [...OTTOMAN_FABRIC, 'Removable Tray'] },
  { key: 'x-bench-ottoman', name: 'X-Bench', category: 'ottoman', subcategory: 'Accent', svgHint: 'bench',
    measurementPoints: OTTOMAN_MEASUREMENTS, fabricSections: ['Top Cushion', 'X-Frame Cover'] },
  { key: 'cube-ottoman', name: 'Cube Ottoman', category: 'ottoman', subcategory: 'Small', svgHint: 'ottoman',
    measurementPoints: ['Size (cube)', 'Height'], fabricSections: ['Top', 'All 4 Sides'] },
  { key: 'pouf-round', name: 'Pouf (Round)', category: 'ottoman', subcategory: 'Casual', svgHint: 'ottoman',
    measurementPoints: ['Diameter', 'Height'], fabricSections: ['Top', 'Side Panel', 'Bottom'] },
  { key: 'pouf-square', name: 'Pouf (Square)', category: 'ottoman', subcategory: 'Casual', svgHint: 'ottoman',
    measurementPoints: ['Width', 'Height'], fabricSections: ['Top', 'Sides (x4)', 'Bottom'] },
  { key: 'floor-cushion', name: 'Floor Cushion', category: 'ottoman', subcategory: 'Casual', svgHint: 'ottoman',
    measurementPoints: ['Width', 'Depth', 'Thickness'], fabricSections: ['Top', 'Bottom', 'Boxing'] },
  { key: 'footstool', name: 'Footstool', category: 'ottoman', subcategory: 'Small', svgHint: 'ottoman',
    measurementPoints: ['Width', 'Depth', 'Height', 'Leg Style'], fabricSections: ['Top Pad', 'Skirt/Base'] },
  { key: 'kilim-ottoman', name: 'Kilim / Rug Ottoman', category: 'ottoman', subcategory: 'Specialty', svgHint: 'ottoman',
    measurementPoints: OTTOMAN_MEASUREMENTS, fabricSections: ['Kilim/Rug Top', 'Leather/Fabric Sides'],
    description: 'Upholstered with antique rug or kilim' },

  // ─────────────────────────────────────────────────────────────
  // BENCHES (15+)
  // ─────────────────────────────────────────────────────────────
  { key: 'bench-flat', name: 'Bench (Flat)', category: 'bench', subcategory: 'Standard', svgHint: 'bench',
    measurementPoints: BENCH_MEASUREMENTS, fabricSections: BENCH_FABRIC },
  { key: 'bench-tufted', name: 'Bench (Tufted)', category: 'bench', subcategory: 'Tufted', svgHint: 'bench',
    measurementPoints: BENCH_MEASUREMENTS, fabricSections: [...BENCH_FABRIC, 'Button Tufting'] },
  { key: 'bench-channel', name: 'Bench (Channel Tufted)', category: 'bench', subcategory: 'Modern', svgHint: 'bench',
    measurementPoints: BENCH_MEASUREMENTS, fabricSections: [...BENCH_FABRIC, 'Channel Tufting'] },
  { key: 'bench-skirted', name: 'Bench (Skirted)', category: 'bench', subcategory: 'Traditional', svgHint: 'bench',
    measurementPoints: BENCH_MEASUREMENTS, fabricSections: [...BENCH_FABRIC, 'Skirt'] },
  { key: 'bench-storage', name: 'Storage Bench', category: 'bench', subcategory: 'Functional', svgHint: 'bench',
    measurementPoints: [...BENCH_MEASUREMENTS, 'Hinge Type'], fabricSections: [...BENCH_FABRIC, 'Lid'] },
  { key: 'window-seat', name: 'Window Seat', category: 'bench', subcategory: 'Built-in', svgHint: 'bench',
    measurementPoints: ['Width', 'Depth', 'Height', 'Bay Angle'],
    fabricSections: ['Top Cushion', 'Front', 'Sides (x2)', 'Back (if freestanding)'] },
  { key: 'entry-bench', name: 'Entry / Mudroom Bench', category: 'bench', subcategory: 'Functional', svgHint: 'bench',
    measurementPoints: BENCH_MEASUREMENTS, fabricSections: ['Seat Cushion', 'Back Panel (optional)', 'Side Arms'] },
  { key: 'piano-bench', name: 'Piano Bench', category: 'bench', subcategory: 'Specialty', svgHint: 'bench',
    measurementPoints: ['Width', 'Depth', 'Height'], fabricSections: ['Top Cushion', 'Skirt (optional)'] },
  { key: 'vanity-bench', name: 'Vanity Bench / Stool', category: 'bench', subcategory: 'Bedroom', svgHint: 'bench',
    measurementPoints: ['Width', 'Depth', 'Height', 'Leg Style'], fabricSections: ['Seat', 'Skirt'] },
  { key: 'luggage-bench', name: 'Luggage Bench', category: 'bench', subcategory: 'Hospitality', svgHint: 'bench',
    measurementPoints: BENCH_MEASUREMENTS, fabricSections: ['Top Strap/Cushion', 'Base'] },
  { key: 'bed-end-bench', name: 'Bed End Bench', category: 'bench', subcategory: 'Bedroom', svgHint: 'bench',
    measurementPoints: BENCH_MEASUREMENTS, fabricSections: BENCH_FABRIC },
  { key: 'settee-bench', name: 'Settee Bench', category: 'bench', subcategory: 'Classic', svgHint: 'bench',
    measurementPoints: [...BENCH_MEASUREMENTS, 'Back Height', 'Arm Height'],
    fabricSections: ['Seat', 'Back', 'Arms', 'Outside Back', 'Skirt'] },
  { key: 'church-pew-cushion', name: 'Church Pew Cushion', category: 'bench', subcategory: 'Specialty', svgHint: 'bench',
    measurementPoints: ['Length', 'Width', 'Thickness', 'Pew Shape'],
    fabricSections: ['Top', 'Boxing', 'Bottom', 'Ties'] },

  // ─────────────────────────────────────────────────────────────
  // BEDS & HEADBOARDS (20+)
  // ─────────────────────────────────────────────────────────────
  { key: 'headboard-rectangular', name: 'Rectangular Headboard', category: 'bed', subcategory: 'Standard', svgHint: 'bed',
    measurementPoints: BED_MEASUREMENTS, fabricSections: HEADBOARD_FABRIC },
  { key: 'headboard-arched', name: 'Arched Headboard', category: 'bed', subcategory: 'Classic', svgHint: 'bed',
    measurementPoints: [...BED_MEASUREMENTS, 'Arch Height'], fabricSections: HEADBOARD_FABRIC },
  { key: 'headboard-camelback', name: 'Camelback Headboard', category: 'bed', subcategory: 'Traditional', svgHint: 'bed',
    measurementPoints: [...BED_MEASUREMENTS, 'Hump Height'], fabricSections: HEADBOARD_FABRIC },
  { key: 'headboard-wingback', name: 'Wingback Headboard', category: 'bed', subcategory: 'Statement', svgHint: 'bed',
    measurementPoints: [...BED_MEASUREMENTS, 'Wing Depth', 'Wing Height'], fabricSections: [...HEADBOARD_FABRIC, 'Inside Wings (x2)', 'Outside Wings (x2)'] },
  { key: 'headboard-tufted', name: 'Button-Tufted Headboard', category: 'bed', subcategory: 'Classic', svgHint: 'bed',
    measurementPoints: [...BED_MEASUREMENTS, 'Tufting Pattern'], fabricSections: [...HEADBOARD_FABRIC, 'Button Tufting'] },
  { key: 'headboard-channel', name: 'Channel-Tufted Headboard', category: 'bed', subcategory: 'Modern', svgHint: 'bed',
    measurementPoints: [...BED_MEASUREMENTS, 'Channel Width'], fabricSections: [...HEADBOARD_FABRIC, 'Channel Tufting'] },
  { key: 'headboard-slipcover', name: 'Slipcover Headboard', category: 'bed', subcategory: 'Casual', svgHint: 'bed',
    measurementPoints: BED_MEASUREMENTS, fabricSections: ['Full Slipcover (removable)'] },
  { key: 'headboard-nailhead', name: 'Nailhead Trim Headboard', category: 'bed', subcategory: 'Transitional', svgHint: 'bed',
    measurementPoints: BED_MEASUREMENTS, fabricSections: [...HEADBOARD_FABRIC, 'Nailhead Border'] },
  { key: 'headboard-panel-tall', name: 'Tall Panel Headboard', category: 'bed', subcategory: 'Modern', svgHint: 'bed',
    measurementPoints: [...BED_MEASUREMENTS, 'Panel Height (to ceiling)'], fabricSections: ['Full Front Panel', 'Side Borders', 'Top Border'] },
  { key: 'upholstered-bed-full', name: 'Fully Upholstered Bed Frame', category: 'bed', subcategory: 'Complete', svgHint: 'bed',
    measurementPoints: [...BED_MEASUREMENTS, 'Footboard Height', 'Side Rail Height'],
    fabricSections: ['Headboard', 'Footboard', 'Side Rails (x2)', 'Platform/Deck'] },
  { key: 'upholstered-bed-platform', name: 'Upholstered Platform Bed', category: 'bed', subcategory: 'Modern', svgHint: 'bed',
    measurementPoints: BED_MEASUREMENTS, fabricSections: ['Headboard', 'Platform Base', 'Side Rails'] },
  { key: 'canopy-bed-upholstered', name: 'Upholstered Canopy Bed', category: 'bed', subcategory: 'Statement', svgHint: 'bed',
    measurementPoints: [...BED_MEASUREMENTS, 'Canopy Height', 'Post Style'],
    fabricSections: ['Headboard', 'Canopy Top', 'Canopy Curtains (x4)', 'Posts Cover'] },
  { key: 'daybed-upholstered', name: 'Upholstered Daybed', category: 'bed', subcategory: 'Dual Use', svgHint: 'bed',
    measurementPoints: ['Width', 'Depth', 'Back Height', 'Arm Heights'], fabricSections: ['Back', 'Arms (x2)', 'Seat/Mattress Cover', 'Bolsters'] },
  { key: 'crib-bumper', name: 'Crib Bumper / Liner', category: 'bed', subcategory: 'Baby', svgHint: 'generic',
    measurementPoints: ['Crib Interior Length', 'Crib Interior Width', 'Bumper Height'],
    fabricSections: ['Bumper Panels (x4)', 'Ties', 'Padding'] },
  { key: 'bed-skirt', name: 'Bed Skirt / Dust Ruffle', category: 'bed', subcategory: 'Accessory', svgHint: 'generic',
    measurementPoints: ['Bed Size', 'Drop Length', 'Style (pleated/gathered/tailored)'],
    fabricSections: ['Platform Panel', 'Front Skirt', 'Side Skirts (x2)', 'Pleats/Gathers'] },

  // ─────────────────────────────────────────────────────────────
  // STOOLS (15+)
  // ─────────────────────────────────────────────────────────────
  { key: 'bar-stool-back', name: 'Bar Stool (With Back)', category: 'chair', subcategory: 'Stool', svgHint: 'stool',
    measurementPoints: STOOL_MEASUREMENTS, fabricSections: ['Seat', 'Back', 'Outside Back'] },
  { key: 'bar-stool-backless', name: 'Bar Stool (Backless)', category: 'chair', subcategory: 'Stool', svgHint: 'stool',
    measurementPoints: ['Seat Width', 'Seat Depth', 'Seat Height'], fabricSections: ['Seat Top', 'Seat Sides'] },
  { key: 'counter-stool-back', name: 'Counter Stool (With Back)', category: 'chair', subcategory: 'Stool', svgHint: 'stool',
    measurementPoints: STOOL_MEASUREMENTS, fabricSections: ['Seat', 'Back', 'Outside Back'] },
  { key: 'counter-stool-backless', name: 'Counter Stool (Backless)', category: 'chair', subcategory: 'Stool', svgHint: 'stool',
    measurementPoints: ['Seat Width', 'Seat Depth', 'Seat Height'], fabricSections: ['Seat Top', 'Seat Sides'] },
  { key: 'swivel-bar-stool', name: 'Swivel Bar Stool', category: 'chair', subcategory: 'Stool', svgHint: 'stool',
    measurementPoints: [...STOOL_MEASUREMENTS, 'Swivel Base Diameter'], fabricSections: ['Seat', 'Back', 'Base Cover'] },
  { key: 'saddle-stool', name: 'Saddle Stool', category: 'chair', subcategory: 'Stool', svgHint: 'stool',
    measurementPoints: ['Seat Width', 'Seat Depth', 'Height'], fabricSections: ['Saddle Seat'] },
  { key: 'step-stool-upholstered', name: 'Step Stool (Upholstered)', category: 'chair', subcategory: 'Stool', svgHint: 'stool',
    measurementPoints: ['Width', 'Depth', 'Height', 'Step Count'], fabricSections: ['Top Step', 'Side Panels', 'Steps'] },

  // ─────────────────────────────────────────────────────────────
  // OUTDOOR / PATIO (15+)
  // ─────────────────────────────────────────────────────────────
  { key: 'outdoor-sofa-cushion', name: 'Outdoor Sofa Cushion Set', category: 'outdoor', subcategory: 'Cushion', svgHint: 'sofa',
    measurementPoints: ['Seat Width', 'Seat Depth', 'Back Height', 'Cushion Count', 'Thickness'],
    fabricSections: ['Seat Cushions', 'Back Cushions', 'Bolsters'] },
  { key: 'outdoor-chair-cushion', name: 'Outdoor Chair Cushion', category: 'outdoor', subcategory: 'Cushion', svgHint: 'chair',
    measurementPoints: ['Width', 'Depth', 'Thickness', 'Shape', 'Tie Locations'],
    fabricSections: ['Top', 'Boxing', 'Bottom', 'Ties'] },
  { key: 'outdoor-chaise-pad', name: 'Outdoor Chaise Lounge Pad', category: 'outdoor', subcategory: 'Cushion', svgHint: 'sofa',
    measurementPoints: ['Length', 'Width', 'Thickness', 'Head Section Length'],
    fabricSections: ['Top', 'Boxing', 'Bottom', 'Head Flap'] },
  { key: 'outdoor-bench-cushion', name: 'Outdoor Bench Cushion', category: 'outdoor', subcategory: 'Cushion', svgHint: 'bench',
    measurementPoints: ['Width', 'Depth', 'Thickness'], fabricSections: ['Top', 'Boxing', 'Bottom', 'Ties'] },
  { key: 'outdoor-swing-cushion', name: 'Porch Swing Cushion', category: 'outdoor', subcategory: 'Cushion', svgHint: 'bench',
    measurementPoints: ['Width', 'Depth', 'Back Height', 'Thickness'], fabricSections: ['Seat', 'Back', 'Ties'] },
  { key: 'outdoor-daybed-cushion', name: 'Outdoor Daybed Cushion Set', category: 'outdoor', subcategory: 'Cushion', svgHint: 'bed',
    measurementPoints: ['Width', 'Depth', 'Mattress Thickness', 'Bolster Count'],
    fabricSections: ['Mattress Cover', 'Bolsters', 'Throw Pillows'] },
  { key: 'boat-cushion', name: 'Boat / Marine Cushion', category: 'outdoor', subcategory: 'Marine', svgHint: 'generic',
    measurementPoints: ['Template Shape', 'Thickness', 'Snap Locations'],
    fabricSections: ['Top', 'Boxing', 'Bottom', 'Snaps/Ties'],
    description: 'Custom shape marine-grade cushions for boats' },
  { key: 'patio-umbrella-cover', name: 'Patio Umbrella Canopy', category: 'outdoor', subcategory: 'Cover', svgHint: 'generic',
    measurementPoints: ['Canopy Diameter', 'Rib Count', 'Pole Diameter'],
    fabricSections: ['Canopy Panels', 'Valance (optional)'] },
  { key: 'outdoor-curtain', name: 'Outdoor Curtain / Cabana', category: 'outdoor', subcategory: 'Drapery', svgHint: 'generic',
    measurementPoints: ['Width', 'Length', 'Hanging Method'], fabricSections: ['Panel', 'Tabs/Grommets'] },
  { key: 'gazebo-curtain', name: 'Gazebo / Pergola Curtain', category: 'outdoor', subcategory: 'Drapery', svgHint: 'generic',
    measurementPoints: ['Width', 'Length', 'Panel Count', 'Tiebacks'],
    fabricSections: ['Panels', 'Tiebacks', 'Header'] },

  // ─────────────────────────────────────────────────────────────
  // COMMERCIAL / HOSPITALITY (15+)
  // ─────────────────────────────────────────────────────────────
  { key: 'restaurant-booth', name: 'Restaurant Booth', category: 'commercial', subcategory: 'Seating', svgHint: 'bench',
    measurementPoints: ['Width', 'Depth', 'Back Height', 'Seat Height', 'Booth Type'],
    fabricSections: ['Seat', 'Back', 'Side Panels', 'Top Cap'] },
  { key: 'booth-single', name: 'Single Booth (Wall-Mount)', category: 'commercial', subcategory: 'Seating', svgHint: 'bench',
    measurementPoints: ['Width', 'Depth', 'Back Height'], fabricSections: ['Seat', 'Back', 'End Panels'] },
  { key: 'booth-double', name: 'Double Booth (Back-to-Back)', category: 'commercial', subcategory: 'Seating', svgHint: 'bench',
    measurementPoints: ['Width', 'Total Depth', 'Back Height', 'Divider Height'],
    fabricSections: ['Seats (x2)', 'Backs (x2)', 'End Panels', 'Divider Cap'] },
  { key: 'waiting-room-chair', name: 'Waiting Room Chair', category: 'commercial', subcategory: 'Healthcare', svgHint: 'chair',
    measurementPoints: CHAIR_MEASUREMENTS, fabricSections: ['Seat', 'Back', 'Arms', 'Vinyl/Leather Cover'] },
  { key: 'medical-exam-cover', name: 'Medical Exam Table Cover', category: 'commercial', subcategory: 'Healthcare', svgHint: 'generic',
    measurementPoints: ['Table Width', 'Table Length', 'Table Height', 'Sections'],
    fabricSections: ['Main Pad', 'Head Section', 'Extension Section'] },
  { key: 'salon-chair-cover', name: 'Salon Chair Cover', category: 'commercial', subcategory: 'Beauty', svgHint: 'chair',
    measurementPoints: ['Seat Width', 'Seat Depth', 'Back Height', 'Arm Style'],
    fabricSections: ['Seat', 'Back', 'Arms', 'Headrest', 'Base Skirt'] },
  { key: 'theater-seat', name: 'Theater / Auditorium Seat', category: 'commercial', subcategory: 'Entertainment', svgHint: 'chair',
    measurementPoints: ['Seat Width', 'Seat Depth', 'Back Height', 'Arm Width', 'Quantity'],
    fabricSections: ['Seat', 'Back', 'Arm Covers', 'Head Panel'] },
  { key: 'church-pew', name: 'Church Pew (Full Reupholster)', category: 'commercial', subcategory: 'Religious', svgHint: 'bench',
    measurementPoints: ['Length', 'Seat Depth', 'Back Height', 'Sections'],
    fabricSections: ['Seat Cushion', 'Back Cushion', 'Book Rack Cover'] },
  { key: 'rv-cushion', name: 'RV / Camper Cushion', category: 'commercial', subcategory: 'Vehicle', svgHint: 'generic',
    measurementPoints: ['Template Required', 'Thickness', 'Piece Count'],
    fabricSections: ['Seat Cushions', 'Back Cushions', 'Bolsters', 'Privacy Curtains'],
    description: 'Custom shape cushions for RV/camper seating and sleeping' },
  { key: 'golf-cart-seat', name: 'Golf Cart Seat Cover', category: 'commercial', subcategory: 'Vehicle', svgHint: 'generic',
    measurementPoints: ['Seat Width', 'Seat Depth', 'Back Height'],
    fabricSections: ['Seat Cover', 'Back Cover', 'Armrest Covers'] },

  // ─────────────────────────────────────────────────────────────
  // ACCENT & DECORATIVE (15+)
  // ─────────────────────────────────────────────────────────────
  { key: 'throw-pillow-square', name: 'Throw Pillow (Square)', category: 'accent', subcategory: 'Pillow', svgHint: 'generic',
    measurementPoints: ['Size (inches)', 'Insert Type'], fabricSections: ['Front', 'Back', 'Welt/Trim'] },
  { key: 'throw-pillow-lumbar', name: 'Throw Pillow (Lumbar)', category: 'accent', subcategory: 'Pillow', svgHint: 'generic',
    measurementPoints: ['Width', 'Height', 'Insert Type'], fabricSections: ['Front', 'Back', 'Welt/Trim'] },
  { key: 'throw-pillow-round', name: 'Throw Pillow (Round)', category: 'accent', subcategory: 'Pillow', svgHint: 'generic',
    measurementPoints: ['Diameter', 'Insert Type'], fabricSections: ['Front', 'Back', 'Button Center'] },
  { key: 'bolster-pillow', name: 'Bolster Pillow', category: 'accent', subcategory: 'Pillow', svgHint: 'generic',
    measurementPoints: ['Length', 'Diameter'], fabricSections: ['Body', 'End Caps (x2)', 'Tassels'] },
  { key: 'euro-sham', name: 'Euro Sham', category: 'accent', subcategory: 'Bedding', svgHint: 'generic',
    measurementPoints: ['Size', 'Flange Width'], fabricSections: ['Front', 'Back', 'Flange'] },
  { key: 'duvet-cover', name: 'Duvet Cover', category: 'accent', subcategory: 'Bedding', svgHint: 'generic',
    measurementPoints: ['Bed Size', 'Drop Length'], fabricSections: ['Top Panel', 'Bottom Panel', 'Closure'] },
  { key: 'bed-runner', name: 'Bed Runner', category: 'accent', subcategory: 'Bedding', svgHint: 'generic',
    measurementPoints: ['Width', 'Length', 'Drop'], fabricSections: ['Top', 'Lining', 'Drop Ends'] },
  { key: 'table-runner', name: 'Table Runner', category: 'accent', subcategory: 'Table', svgHint: 'generic',
    measurementPoints: ['Width', 'Length', 'Drop'], fabricSections: ['Top', 'Lining', 'Drop Ends', 'Trim'] },
  { key: 'tablecloth', name: 'Tablecloth (Custom)', category: 'accent', subcategory: 'Table', svgHint: 'generic',
    measurementPoints: ['Table Shape', 'Table Diameter/Dimensions', 'Drop Length'],
    fabricSections: ['Top', 'Drop Sides', 'Hem/Trim'] },
  { key: 'screen-panel', name: 'Upholstered Screen / Room Divider', category: 'accent', subcategory: 'Decor', svgHint: 'generic',
    measurementPoints: ['Panel Width', 'Panel Height', 'Panel Count', 'Hinge Type'],
    fabricSections: ['Front Panels', 'Back Panels', 'Top/Bottom Rails'] },
  { key: 'wall-panel', name: 'Upholstered Wall Panel', category: 'accent', subcategory: 'Decor', svgHint: 'generic',
    measurementPoints: ['Width', 'Height', 'Depth/Padding Thickness', 'Panel Count'],
    fabricSections: ['Front Face', 'Side Returns', 'Tufting/Channel (optional)'] },
  { key: 'cornice-padded', name: 'Padded / Upholstered Cornice', category: 'accent', subcategory: 'Window', svgHint: 'generic',
    measurementPoints: ['Width', 'Height', 'Return Depth', 'Shape'],
    fabricSections: ['Front Face', 'Returns (x2)', 'Top', 'Lining'] },
  { key: 'pelmet-upholstered', name: 'Upholstered Pelmet', category: 'accent', subcategory: 'Window', svgHint: 'generic',
    measurementPoints: ['Width', 'Height', 'Return Depth', 'Shape (straight/shaped)'],
    fabricSections: ['Front Face', 'Returns (x2)', 'Bottom Edge Trim'] },
  { key: 'lampshade', name: 'Custom Lampshade', category: 'accent', subcategory: 'Lighting', svgHint: 'generic',
    measurementPoints: ['Top Diameter', 'Bottom Diameter', 'Slant Height', 'Shape'],
    fabricSections: ['Shade Panel', 'Lining', 'Top/Bottom Trim'] },

  // ─────────────────────────────────────────────────────────────
  // WOODCRAFT / CNC — Tables, Cabinets, Custom (20+)
  // ─────────────────────────────────────────────────────────────
  { key: 'dining-table', name: 'Dining Table', category: 'table', subcategory: 'Dining', svgHint: 'table',
    measurementPoints: ['Length', 'Width', 'Height', 'Leg Style', 'Seating Capacity'],
    fabricSections: ['Table Pad (optional)', 'Leaf Covers'] },
  { key: 'coffee-table', name: 'Coffee Table', category: 'table', subcategory: 'Living', svgHint: 'table',
    measurementPoints: ['Length', 'Width', 'Height', 'Shape', 'Shelf'],
    fabricSections: ['Table Pad (optional)'] },
  { key: 'console-table', name: 'Console Table', category: 'table', subcategory: 'Accent', svgHint: 'table',
    measurementPoints: ['Width', 'Depth', 'Height', 'Shelf Count'],
    fabricSections: ['Table Pad (optional)'] },
  { key: 'end-table', name: 'End Table / Side Table', category: 'table', subcategory: 'Accent', svgHint: 'table',
    measurementPoints: ['Width/Diameter', 'Height', 'Shelf'],
    fabricSections: ['Table Pad (optional)'] },
  { key: 'nightstand', name: 'Nightstand', category: 'table', subcategory: 'Bedroom', svgHint: 'table',
    measurementPoints: ['Width', 'Depth', 'Height', 'Drawer Count'],
    fabricSections: [] },
  { key: 'desk-custom', name: 'Custom Desk', category: 'table', subcategory: 'Office', svgHint: 'table',
    measurementPoints: ['Width', 'Depth', 'Height', 'Drawer Configuration', 'Cable Management'],
    fabricSections: ['Desktop Pad (optional)', 'Modesty Panel'] },
  { key: 'bookshelf', name: 'Custom Bookshelf', category: 'storage', subcategory: 'Storage', svgHint: 'cabinet',
    measurementPoints: ['Width', 'Depth', 'Height', 'Shelf Count', 'Adjustable'],
    fabricSections: [] },
  { key: 'built-in-cabinet', name: 'Built-In Cabinet', category: 'storage', subcategory: 'Built-In', svgHint: 'cabinet',
    measurementPoints: ['Width', 'Depth', 'Height', 'Door Style', 'Shelf Count'],
    fabricSections: [] },
  { key: 'entertainment-center', name: 'Entertainment Center', category: 'storage', subcategory: 'Living', svgHint: 'cabinet',
    measurementPoints: ['Width', 'Depth', 'Height', 'TV Opening', 'Component Shelves'],
    fabricSections: [] },
  { key: 'wine-rack', name: 'Wine Rack / Bar Cabinet', category: 'storage', subcategory: 'Bar', svgHint: 'cabinet',
    measurementPoints: ['Width', 'Depth', 'Height', 'Bottle Capacity', 'Glass Rack'],
    fabricSections: [] },
  { key: 'closet-system', name: 'Custom Closet System', category: 'storage', subcategory: 'Closet', svgHint: 'cabinet',
    measurementPoints: ['Closet Width', 'Closet Depth', 'Closet Height', 'Hanging Sections', 'Drawer Sections', 'Shelf Sections'],
    fabricSections: [] },
  { key: 'floating-shelf', name: 'Floating Shelf', category: 'storage', subcategory: 'Wall', svgHint: 'generic',
    measurementPoints: ['Width', 'Depth', 'Thickness', 'Quantity'],
    fabricSections: [] },
  { key: 'mantel', name: 'Fireplace Mantel', category: 'table', subcategory: 'Architectural', svgHint: 'generic',
    measurementPoints: ['Mantel Width', 'Shelf Depth', 'Height', 'Surround Dimensions'],
    fabricSections: [] },
  { key: 'crown-molding', name: 'Custom Crown Molding', category: 'other', subcategory: 'Millwork', svgHint: 'generic',
    measurementPoints: ['Profile Height', 'Projection', 'Total Linear Feet', 'Corner Count'],
    fabricSections: [] },
  { key: 'wainscoting', name: 'Wainscoting / Wall Paneling', category: 'other', subcategory: 'Millwork', svgHint: 'generic',
    measurementPoints: ['Wall Length', 'Panel Height', 'Panel Style', 'Chair Rail Height'],
    fabricSections: [] },
  { key: 'stair-railing', name: 'Custom Stair Railing', category: 'other', subcategory: 'Millwork', svgHint: 'generic',
    measurementPoints: ['Total Run', 'Rise', 'Baluster Style', 'Newel Post Style'],
    fabricSections: [] },
  { key: 'picture-frame', name: 'Custom Picture Frame', category: 'other', subcategory: 'Millwork', svgHint: 'generic',
    measurementPoints: ['Opening Width', 'Opening Height', 'Profile Width', 'Mat Width'],
    fabricSections: [] },
  { key: 'mirror-frame', name: 'Custom Mirror Frame', category: 'other', subcategory: 'Millwork', svgHint: 'generic',
    measurementPoints: ['Mirror Width', 'Mirror Height', 'Frame Profile', 'Shape'],
    fabricSections: [] },
];
