/**
 * Empire Window Treatment Catalog — Comprehensive type library
 * Every window treatment style Empire Workroom can fabricate.
 * Each has measurement points, fabric sections, and a basic SVG hint.
 */

export interface WindowTreatmentType {
  key: string;
  name: string;
  category: 'drapery' | 'shade' | 'valance' | 'blind' | 'shutter' | 'specialty' | 'hardware' | 'accessory';
  subcategory?: string;
  measurementPoints: string[];
  fabricSections: string[];
  description?: string;
  svgHint?: string;
}

export const WT_CATEGORY_LABELS: Record<string, string> = {
  drapery: 'Drapery',
  shade: 'Shade',
  valance: 'Valance',
  blind: 'Blind',
  shutter: 'Shutter',
  specialty: 'Specialty',
  hardware: 'Hardware',
  accessory: 'Accessory',
};

// ── Standard measurement sets ─────────────────────────────────

const DRAPERY_MEASUREMENTS = [
  'Finished Width', 'Finished Length', 'Rod/Track Width',
  'Stackback Space', 'Mount Type (inside/outside)',
  'Rod Height from Floor', 'Window Width', 'Window Height',
];

const SHADE_MEASUREMENTS = [
  'Finished Width', 'Finished Length',
  'Mount Type (inside/outside)', 'Window Depth',
  'Bracket Clearance',
];

const VALANCE_MEASUREMENTS = [
  'Finished Width', 'Finished Length/Drop',
  'Return Depth', 'Mount Type',
];

// ═══════════════════════════════════════════════════════════════
// WINDOW TREATMENT CATALOG — 130+ items
// ═══════════════════════════════════════════════════════════════

export const WINDOW_TREATMENT_TYPES: WindowTreatmentType[] = [

  // ─────────────────────────────────────────────────────────────
  // DRAPERY — Pleat Styles (20+)
  // ─────────────────────────────────────────────────────────────
  { key: 'pinch-pleat-drapery', name: 'Pinch Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Pleat Count', 'Pleat Spacing'],
    fabricSections: ['Face Fabric', 'Lining', 'Interlining (optional)', 'Header', 'Hem', 'Leading Edge'],
    description: 'Classic three-finger pinch pleat, most popular traditional style' },
  { key: 'french-pleat-drapery', name: 'French Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Pleat Size'],
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem'],
    description: 'Three-finger pleat fanning outward, elegant formal look' },
  { key: 'goblet-pleat-drapery', name: 'Goblet Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Goblet Height'],
    fabricSections: ['Face Fabric', 'Lining', 'Goblet Fill', 'Header', 'Hem'],
    description: 'Cylindrical cup-shaped pleat, stationary panels' },
  { key: 'cartridge-pleat-drapery', name: 'Cartridge Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Cartridge Diameter'],
    fabricSections: ['Face Fabric', 'Lining', 'Cartridge Roll Fill', 'Header', 'Hem'],
    description: 'Round cylindrical pleat, similar to goblet without the cup' },
  { key: 'euro-pleat-drapery', name: 'Euro Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: DRAPERY_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem'],
    description: 'Two-finger pleat, slightly more casual than pinch pleat' },
  { key: 'inverted-pleat-drapery', name: 'Inverted Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: DRAPERY_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem'],
    description: 'Pleat folds concealed behind panel, clean front appearance' },
  { key: 'box-pleat-drapery', name: 'Box Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Pleat Width'],
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem'],
    description: 'Flat symmetrical pleats, crisp tailored look' },
  { key: 'pencil-pleat-drapery', name: 'Pencil Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: DRAPERY_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Pencil Pleat Tape', 'Hem'],
    description: 'Tight cylindrical pleats using header tape, versatile' },
  { key: 'butterfly-pleat-drapery', name: 'Butterfly Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: DRAPERY_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem'],
    description: 'Double pleat spreading outward like butterfly wings' },
  { key: 'parisian-pleat-drapery', name: 'Parisian Pleat Drapery', category: 'drapery', subcategory: 'Pleated', svgHint: 'drapery',
    measurementPoints: DRAPERY_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem'],
    description: 'Single deep pleat, minimalist and modern' },

  // ── DRAPERY — Non-Pleat Styles ──
  { key: 'ripplefold-drapery', name: 'Ripplefold Drapery', category: 'drapery', subcategory: 'Track', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Carrier Spacing', 'Track Length'],
    fabricSections: ['Face Fabric', 'Lining', 'Snap Tape', 'Hem'],
    description: 'Uniform S-curve folds on track system, contemporary' },
  { key: 'grommet-drapery', name: 'Grommet / Eyelet Drapery', category: 'drapery', subcategory: 'Casual', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Grommet Size', 'Grommet Color'],
    fabricSections: ['Face Fabric', 'Lining', 'Grommet Band', 'Hem'],
    description: 'Metal grommets threaded on rod, casual modern look' },
  { key: 'rod-pocket-drapery', name: 'Rod Pocket Drapery', category: 'drapery', subcategory: 'Casual', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Pocket Size', 'Header Ruffle Height'],
    fabricSections: ['Face Fabric', 'Lining', 'Rod Pocket', 'Ruffle Header', 'Hem'],
    description: 'Fabric sewn into pocket that slides over rod, gathered look' },
  { key: 'tab-top-drapery', name: 'Tab Top Drapery', category: 'drapery', subcategory: 'Casual', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Tab Width', 'Tab Length'],
    fabricSections: ['Face Fabric', 'Lining', 'Fabric Tabs', 'Hem'],
    description: 'Fabric loops over rod, relaxed cottage style' },
  { key: 'tie-top-drapery', name: 'Tie Top Drapery', category: 'drapery', subcategory: 'Casual', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Tie Length'],
    fabricSections: ['Face Fabric', 'Lining', 'Tie Strips', 'Hem'],
    description: 'Fabric ties knotted or bowed over rod' },
  { key: 'ring-clip-drapery', name: 'Ring & Clip Drapery', category: 'drapery', subcategory: 'Casual', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Ring Size', 'Clip Spacing'],
    fabricSections: ['Face Fabric', 'Lining', 'Hem'],
    description: 'Flat panel hung with decorative rings and clips' },
  { key: 'flat-panel-drapery', name: 'Flat Panel Drapery', category: 'drapery', subcategory: 'Modern', svgHint: 'drapery',
    measurementPoints: DRAPERY_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem'],
    description: 'No fullness, clean straight panels, contemporary' },
  { key: 'sheer-drapery', name: 'Sheer Drapery', category: 'drapery', subcategory: 'Sheer', svgHint: 'drapery',
    measurementPoints: DRAPERY_MEASUREMENTS,
    fabricSections: ['Sheer Fabric', 'Double Hem', 'Header'],
    description: 'Lightweight translucent fabric, any pleat style' },
  { key: 'blackout-drapery', name: 'Blackout Drapery', category: 'drapery', subcategory: 'Functional', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Light Gap Coverage'],
    fabricSections: ['Face Fabric', 'Blackout Lining', 'Header', 'Hem', 'Side Seals'],
    description: 'Full light-blocking with blackout lining and overlap' },
  { key: 'thermal-drapery', name: 'Thermal / Insulated Drapery', category: 'drapery', subcategory: 'Functional', svgHint: 'drapery',
    measurementPoints: DRAPERY_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Thermal Lining', 'Interlining', 'Header', 'Hem'],
    description: 'Extra insulation layer for energy efficiency' },
  { key: 'motorized-drapery', name: 'Motorized Drapery', category: 'drapery', subcategory: 'Smart', svgHint: 'drapery',
    measurementPoints: [...DRAPERY_MEASUREMENTS, 'Motor Side', 'Power Source', 'Smart Hub'],
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem'],
    description: 'Motorized track system with remote/app control' },
  { key: 'stationary-panel', name: 'Stationary Side Panel', category: 'drapery', subcategory: 'Decorative', svgHint: 'drapery',
    measurementPoints: ['Panel Width', 'Panel Length', 'Mount Point'],
    fabricSections: ['Face Fabric', 'Lining', 'Header', 'Hem', 'Tieback'],
    description: 'Non-functional decorative panels flanking a window' },
  { key: 'cafe-curtain', name: 'Café Curtain', category: 'drapery', subcategory: 'Casual', svgHint: 'drapery',
    measurementPoints: ['Window Width', 'Curtain Length', 'Rod Height', 'Mount Type'],
    fabricSections: ['Face Fabric', 'Rod Pocket/Tabs', 'Hem'],
    description: 'Half-window curtain, covers lower portion only' },
  { key: 'door-panel', name: 'Door Panel Curtain', category: 'drapery', subcategory: 'Specialty', svgHint: 'drapery',
    measurementPoints: ['Door Glass Width', 'Door Glass Height', 'Top Rod', 'Bottom Rod'],
    fabricSections: ['Face Fabric', 'Rod Pockets (x2)', 'Hem'],
    description: 'Sidelight or French door panel with top and bottom rods' },
  { key: 'arched-window-drapery', name: 'Arched Window Treatment', category: 'drapery', subcategory: 'Specialty', svgHint: 'drapery',
    measurementPoints: ['Window Width', 'Straight Height', 'Arch Height', 'Arch Radius'],
    fabricSections: ['Face Fabric', 'Arch Section', 'Straight Section', 'Lining'],
    description: 'Custom panel shaped to fit arched or Palladian windows' },

  // ─────────────────────────────────────────────────────────────
  // SHADES (30+)
  // ─────────────────────────────────────────────────────────────
  { key: 'roman-flat', name: 'Flat Roman Shade', category: 'shade', subcategory: 'Roman', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS, fabricSections: ['Face Fabric', 'Lining', 'Dowel Pockets', 'Bottom Bar'] },
  { key: 'roman-hobbled', name: 'Hobbled / Teardrop Roman Shade', category: 'shade', subcategory: 'Roman', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Face Fabric (2× fullness)', 'Lining', 'Ring Tape', 'Bottom Bar'],
    description: 'Soft cascading folds when lowered and raised' },
  { key: 'roman-relaxed', name: 'Relaxed / European Roman Shade', category: 'shade', subcategory: 'Roman', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Soft Swag Bottom'],
    description: 'No dowels, gentle swag curve at bottom' },
  { key: 'roman-balloon', name: 'Balloon Roman Shade', category: 'shade', subcategory: 'Roman', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Face Fabric (2.5× fullness)', 'Lining', 'Ring Tape', 'Bottom Rosettes'],
    description: 'Billowing puffs when raised, full and romantic' },
  { key: 'roman-austrian', name: 'Austrian Shade', category: 'shade', subcategory: 'Roman', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Sheer/Lightweight Fabric (3× fullness)', 'Shirring Tape', 'Bottom Fringe'],
    description: 'Vertically shirred with scalloped bottom, theatrical' },
  { key: 'roman-london', name: 'London Shade', category: 'shade', subcategory: 'Roman', svgHint: 'shade',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Inverted Pleat Spacing'],
    fabricSections: ['Face Fabric', 'Lining', 'Inverted Pleats', 'Bottom Trim'],
    description: 'Inverted box pleats creating soft tails when raised' },
  { key: 'roman-cascade', name: 'Cascade Roman Shade', category: 'shade', subcategory: 'Roman', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Fold Overlap Sections'],
    description: 'Overlapping folds that cascade like a waterfall' },
  { key: 'roman-tulip', name: 'Tulip Roman Shade', category: 'shade', subcategory: 'Roman', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Inverted Pleat Section'],
    description: 'Similar to London with single center inverted pleat' },
  { key: 'roman-motorized', name: 'Motorized Roman Shade', category: 'shade', subcategory: 'Smart', svgHint: 'shade',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Motor Type', 'Power Source'],
    fabricSections: ['Face Fabric', 'Lining', 'Motor Housing'],
    description: 'Any roman style with motorized lift mechanism' },
  { key: 'roller-shade', name: 'Roller Shade (Fabric)', category: 'shade', subcategory: 'Roller', svgHint: 'shade',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Roll Direction (standard/reverse)'],
    fabricSections: ['Face Fabric (stiffened)', 'Bottom Bar', 'Cassette (optional)'],
    description: 'Flat fabric rolling around tube, clean minimal look' },
  { key: 'solar-shade', name: 'Solar / Screen Shade', category: 'shade', subcategory: 'Roller', svgHint: 'shade',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Openness Factor (1-14%)'],
    fabricSections: ['Solar Screen Fabric', 'Bottom Bar'],
    description: 'UV-blocking mesh that preserves outward view' },
  { key: 'dual-roller-shade', name: 'Dual Roller Shade', category: 'shade', subcategory: 'Roller', svgHint: 'shade',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Front Fabric', 'Back Fabric'],
    fabricSections: ['Sheer Layer', 'Blackout Layer', 'Dual Cassette'],
    description: 'Two rollers — sheer in front, blackout behind' },
  { key: 'woven-wood-shade', name: 'Woven Wood / Bamboo Shade', category: 'shade', subcategory: 'Natural', svgHint: 'shade',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Weave Style'],
    fabricSections: ['Woven Wood Panel', 'Privacy Liner (optional)', 'Edge Binding'],
    description: 'Natural materials woven into flat or hobbled shade' },
  { key: 'pleated-shade', name: 'Pleated Shade', category: 'shade', subcategory: 'Cellular', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Pleated Fabric', 'Cord/Cordless System'],
    description: 'Accordion-folded single layer of fabric' },
  { key: 'cellular-shade', name: 'Cellular / Honeycomb Shade', category: 'shade', subcategory: 'Cellular', svgHint: 'shade',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Cell Size (single/double/triple)'],
    fabricSections: ['Cellular Fabric', 'Top/Bottom Rails'],
    description: 'Honeycomb cells trap air for insulation' },
  { key: 'top-down-bottom-up', name: 'Top-Down Bottom-Up Shade', category: 'shade', subcategory: 'Functional', svgHint: 'shade',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Dual Rail System'],
    description: 'Opens from top or bottom independently' },

  // ─────────────────────────────────────────────────────────────
  // VALANCES & TOP TREATMENTS (25+)
  // ─────────────────────────────────────────────────────────────
  { key: 'box-pleat-valance', name: 'Box Pleat Valance', category: 'valance', subcategory: 'Pleated', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS, fabricSections: ['Face Fabric', 'Lining', 'Pleats', 'Bottom Trim'] },
  { key: 'pinch-pleat-valance', name: 'Pinch Pleat Valance', category: 'valance', subcategory: 'Pleated', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS, fabricSections: ['Face Fabric', 'Lining', 'Pleats'] },
  { key: 'rod-pocket-valance', name: 'Rod Pocket Valance', category: 'valance', subcategory: 'Gathered', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS, fabricSections: ['Face Fabric', 'Rod Pocket', 'Lining'] },
  { key: 'gathered-valance', name: 'Gathered / Shirred Valance', category: 'valance', subcategory: 'Gathered', svgHint: 'valance',
    measurementPoints: [...VALANCE_MEASUREMENTS, 'Fullness Ratio'],
    fabricSections: ['Face Fabric', 'Lining', 'Gathering Tape'] },
  { key: 'balloon-valance', name: 'Balloon Valance', category: 'valance', subcategory: 'Soft', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS, fabricSections: ['Face Fabric', 'Lining', 'Puff Sections'] },
  { key: 'cloud-valance', name: 'Cloud Valance', category: 'valance', subcategory: 'Soft', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS, fabricSections: ['Face Fabric', 'Lining', 'Pouf Bottom'] },
  { key: 'swag-and-jabot', name: 'Swag & Jabot', category: 'valance', subcategory: 'Formal', svgHint: 'valance',
    measurementPoints: [...VALANCE_MEASUREMENTS, 'Swag Depth', 'Jabot Length', 'Number of Swags'],
    fabricSections: ['Swag Fabric', 'Jabot Fabric', 'Lining', 'Fringe/Trim'],
    description: 'Draped fabric swags with pleated side tails' },
  { key: 'swag-cascade', name: 'Swag with Cascade', category: 'valance', subcategory: 'Formal', svgHint: 'valance',
    measurementPoints: [...VALANCE_MEASUREMENTS, 'Swag Depth', 'Cascade Length'],
    fabricSections: ['Swag', 'Cascades (x2)', 'Lining', 'Trim'] },
  { key: 'kingston-valance', name: 'Kingston Valance', category: 'valance', subcategory: 'Formal', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Self-Lined Tails', 'Trim'] },
  { key: 'empire-valance', name: 'Empire Valance', category: 'valance', subcategory: 'Formal', svgHint: 'valance',
    measurementPoints: [...VALANCE_MEASUREMENTS, 'Gathered Section Width'],
    fabricSections: ['Flat Top Section', 'Gathered Bottom Section', 'Lining'] },
  { key: 'cornice-upholstered', name: 'Upholstered Cornice', category: 'valance', subcategory: 'Structured', svgHint: 'valance',
    measurementPoints: [...VALANCE_MEASUREMENTS, 'Shape (straight/scalloped/shaped)'],
    fabricSections: ['Face Fabric', 'Padding', 'Board Cover', 'Returns', 'Bottom Trim'] },
  { key: 'cornice-shaped', name: 'Shaped Cornice (Custom)', category: 'valance', subcategory: 'Structured', svgHint: 'valance',
    measurementPoints: [...VALANCE_MEASUREMENTS, 'Template/Pattern'],
    fabricSections: ['Face Fabric', 'Padding', 'Custom Shape Board', 'Trim'] },
  { key: 'pelmet', name: 'Pelmet', category: 'valance', subcategory: 'Structured', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS, fabricSections: ['Face Fabric', 'Board', 'Returns', 'Trim'] },
  { key: 'lambrequin', name: 'Lambrequin', category: 'valance', subcategory: 'Structured', svgHint: 'valance',
    measurementPoints: [...VALANCE_MEASUREMENTS, 'Side Drop Length'],
    fabricSections: ['Face Fabric', 'Board', 'Side Panels', 'Trim'],
    description: 'Cornice that extends down the sides of the window' },
  { key: 'scarf-valance', name: 'Scarf / Draped Valance', category: 'valance', subcategory: 'Casual', svgHint: 'valance',
    measurementPoints: ['Scarf Length', 'Swag Depth', 'Tail Lengths'],
    fabricSections: ['Scarf Fabric', 'Lining (optional)'] },
  { key: 'pole-swag', name: 'Pole Swag', category: 'valance', subcategory: 'Casual', svgHint: 'valance',
    measurementPoints: ['Rod Width', 'Swag Depth', 'Tail Lengths'],
    fabricSections: ['Swag Fabric', 'Lining'] },
  { key: 'board-mounted-flat', name: 'Board-Mounted Flat Valance', category: 'valance', subcategory: 'Tailored', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Board Wrap', 'Returns'] },
  { key: 'arched-valance', name: 'Arched / Scalloped Valance', category: 'valance', subcategory: 'Shaped', svgHint: 'valance',
    measurementPoints: [...VALANCE_MEASUREMENTS, 'Arch Depth'],
    fabricSections: ['Face Fabric', 'Shaped Bottom Edge', 'Trim'] },
  { key: 'handkerchief-valance', name: 'Handkerchief Valance', category: 'valance', subcategory: 'Casual', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Pointed Hem'],
    description: 'Fabric draped diagonally with pointed hem' },
  { key: 'butterfly-valance', name: 'Butterfly Valance', category: 'valance', subcategory: 'Soft', svgHint: 'valance',
    measurementPoints: VALANCE_MEASUREMENTS,
    fabricSections: ['Face Fabric', 'Lining', 'Tied Center', 'Tails'] },

  // ─────────────────────────────────────────────────────────────
  // BLINDS (10+)
  // ─────────────────────────────────────────────────────────────
  { key: 'venetian-blind-wood', name: 'Wood Venetian Blind', category: 'blind', subcategory: 'Horizontal', svgHint: 'blind',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Slat Width (1"/2"/2.5")'],
    fabricSections: ['Wood Slats', 'Ladder Tape/Cord', 'Headrail', 'Bottom Rail'] },
  { key: 'venetian-blind-faux', name: 'Faux Wood Blind', category: 'blind', subcategory: 'Horizontal', svgHint: 'blind',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Slat Width'],
    fabricSections: ['Composite Slats', 'Ladder System', 'Rails'] },
  { key: 'venetian-blind-aluminum', name: 'Aluminum Mini Blind', category: 'blind', subcategory: 'Horizontal', svgHint: 'blind',
    measurementPoints: [...SHADE_MEASUREMENTS, 'Slat Width (1/2"/1")'],
    fabricSections: ['Aluminum Slats', 'Rails'] },
  { key: 'vertical-blind-fabric', name: 'Vertical Blind (Fabric)', category: 'blind', subcategory: 'Vertical', svgHint: 'blind',
    measurementPoints: ['Track Width', 'Vane Length', 'Stack Side'],
    fabricSections: ['Fabric Vanes', 'Track System'] },
  { key: 'vertical-blind-vinyl', name: 'Vertical Blind (Vinyl)', category: 'blind', subcategory: 'Vertical', svgHint: 'blind',
    measurementPoints: ['Track Width', 'Vane Length', 'Stack Side'],
    fabricSections: ['PVC Vanes', 'Track System'] },
  { key: 'panel-track-blind', name: 'Panel Track Blind', category: 'blind', subcategory: 'Panel', svgHint: 'blind',
    measurementPoints: ['Track Width', 'Panel Width', 'Panel Length', 'Panel Count'],
    fabricSections: ['Fabric Panels', 'Track System', 'Bottom Weights'] },
  { key: 'sheer-horizontal-blind', name: 'Sheer Horizontal Shade (Silhouette-style)', category: 'blind', subcategory: 'Sheer', svgHint: 'blind',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Sheer Face', 'Fabric Vanes', 'Sheer Back'],
    description: 'Fabric vanes floating between sheer layers' },
  { key: 'zebra-blind', name: 'Zebra / Dual Shade', category: 'blind', subcategory: 'Dual', svgHint: 'blind',
    measurementPoints: SHADE_MEASUREMENTS,
    fabricSections: ['Alternating Sheer/Opaque Bands'],
    description: 'Alternating sheer and solid bands that align for light control' },

  // ─────────────────────────────────────────────────────────────
  // SHUTTERS (8+)
  // ─────────────────────────────────────────────────────────────
  { key: 'plantation-shutter', name: 'Plantation Shutter', category: 'shutter', subcategory: 'Interior', svgHint: 'shutter',
    measurementPoints: ['Window Width', 'Window Height', 'Window Depth', 'Louver Size (2.5"/3.5"/4.5")', 'Panel Count', 'Hinge Side'],
    fabricSections: ['Frame', 'Louvers', 'Stile', 'Tilt Bar'] },
  { key: 'cafe-shutter', name: 'Café Shutter (Half)', category: 'shutter', subcategory: 'Interior', svgHint: 'shutter',
    measurementPoints: ['Window Width', 'Shutter Height', 'Louver Size'],
    fabricSections: ['Frame', 'Louvers', 'Stile'] },
  { key: 'full-height-shutter', name: 'Full Height Shutter', category: 'shutter', subcategory: 'Interior', svgHint: 'shutter',
    measurementPoints: ['Window Width', 'Window Height', 'Divider Rail Height', 'Louver Size'],
    fabricSections: ['Frame', 'Upper Louvers', 'Lower Louvers', 'Divider Rail'] },
  { key: 'tier-on-tier-shutter', name: 'Tier-on-Tier Shutter', category: 'shutter', subcategory: 'Interior', svgHint: 'shutter',
    measurementPoints: ['Window Width', 'Window Height', 'Tier Heights', 'Louver Size'],
    fabricSections: ['Frame', 'Upper Tier Panels', 'Lower Tier Panels'] },
  { key: 'solid-panel-shutter', name: 'Solid Panel Shutter', category: 'shutter', subcategory: 'Interior', svgHint: 'shutter',
    measurementPoints: ['Window Width', 'Window Height', 'Panel Style'],
    fabricSections: ['Frame', 'Solid Panels', 'Optional Fabric Insert'] },
  { key: 'bi-fold-shutter', name: 'Bi-Fold Shutter', category: 'shutter', subcategory: 'Wide Opening', svgHint: 'shutter',
    measurementPoints: ['Opening Width', 'Opening Height', 'Panel Count', 'Fold Direction'],
    fabricSections: ['Frame', 'Louver Panels', 'Track System'] },
  { key: 'barn-door-shutter', name: 'Barn Door Shutter', category: 'shutter', subcategory: 'Sliding', svgHint: 'shutter',
    measurementPoints: ['Opening Width', 'Opening Height', 'Panel Count', 'Track Length'],
    fabricSections: ['Frame', 'Panels (louvered or solid)', 'Track Hardware'] },
  { key: 'exterior-shutter', name: 'Exterior Shutter', category: 'shutter', subcategory: 'Exterior', svgHint: 'shutter',
    measurementPoints: ['Window Width', 'Window Height', 'Style (louvered/raised panel/board & batten)'],
    fabricSections: ['Panel', 'Hardware'] },

  // ─────────────────────────────────────────────────────────────
  // SPECIALTY (15+)
  // ─────────────────────────────────────────────────────────────
  { key: 'canopy-bed-drapery', name: 'Bed Canopy Drapery', category: 'specialty', subcategory: 'Bed', svgHint: 'drapery',
    measurementPoints: ['Canopy Frame Dimensions', 'Panel Length', 'Panel Count'],
    fabricSections: ['Canopy Top', 'Side Panels', 'Head Panel', 'Tiebacks'] },
  { key: 'corona-crown', name: 'Corona / Bed Crown', category: 'specialty', subcategory: 'Bed', svgHint: 'valance',
    measurementPoints: ['Crown Width', 'Cascade Length', 'Panel Width'],
    fabricSections: ['Crown Cover', 'Side Cascades', 'Back Panel', 'Lining'] },
  { key: 'shower-curtain', name: 'Custom Shower Curtain', category: 'specialty', subcategory: 'Bath', svgHint: 'drapery',
    measurementPoints: ['Width', 'Length', 'Hook Style', 'Valance (yes/no)'],
    fabricSections: ['Face Fabric', 'Liner', 'Valance (optional)', 'Tiebacks'] },
  { key: 'window-film', name: 'Decorative Window Film', category: 'specialty', subcategory: 'Film', svgHint: 'generic',
    measurementPoints: ['Window Width', 'Window Height', 'Pattern'],
    fabricSections: ['Film Panel'] },
  { key: 'skylight-shade', name: 'Skylight Shade', category: 'specialty', subcategory: 'Skylight', svgHint: 'shade',
    measurementPoints: ['Skylight Width', 'Skylight Length', 'Angle', 'Shade Type'],
    fabricSections: ['Face Fabric', 'Side Channels', 'Motor (if motorized)'] },
  { key: 'transom-treatment', name: 'Transom Window Treatment', category: 'specialty', subcategory: 'Specialty Window', svgHint: 'shade',
    measurementPoints: ['Transom Width', 'Transom Height', 'Shape (rectangular/arched/half-round)'],
    fabricSections: ['Shaped Fabric', 'Frame Mounted'] },
  { key: 'bay-window-treatment', name: 'Bay Window Treatment', category: 'specialty', subcategory: 'Bay', svgHint: 'drapery',
    measurementPoints: ['Center Width', 'Side Widths', 'Angles', 'Total Span', 'Length'],
    fabricSections: ['Center Panel', 'Side Panels', 'Returns', 'Lining'] },
  { key: 'bow-window-treatment', name: 'Bow Window Treatment', category: 'specialty', subcategory: 'Bay', svgHint: 'drapery',
    measurementPoints: ['Curve Radius', 'Number of Sections', 'Total Span', 'Length'],
    fabricSections: ['Curved Track Panels', 'Lining'] },
  { key: 'corner-window', name: 'Corner Window Treatment', category: 'specialty', subcategory: 'Corner', svgHint: 'drapery',
    measurementPoints: ['Left Width', 'Right Width', 'Length', 'Corner Angle'],
    fabricSections: ['Left Panel', 'Right Panel', 'Corner Meeting'] },
  { key: 'sliding-door-treatment', name: 'Sliding Glass Door Treatment', category: 'specialty', subcategory: 'Door', svgHint: 'drapery',
    measurementPoints: ['Opening Width', 'Length', 'Stack Side', 'One-way or Split'],
    fabricSections: ['Panels', 'Header', 'Hem'] },
  { key: 'french-door-treatment', name: 'French Door Treatment', category: 'specialty', subcategory: 'Door', svgHint: 'drapery',
    measurementPoints: ['Door Width', 'Door Height', 'Top Mount', 'Bottom Mount'],
    fabricSections: ['Door Panel', 'Rod Pockets (x2)', 'Magnetic Hold'] },

  // ─────────────────────────────────────────────────────────────
  // HARDWARE (10+)
  // ─────────────────────────────────────────────────────────────
  { key: 'decorative-rod', name: 'Decorative Rod & Finials', category: 'hardware', subcategory: 'Rod', svgHint: 'generic',
    measurementPoints: ['Rod Width', 'Rod Diameter', 'Finial Style', 'Bracket Count', 'Finish'],
    fabricSections: [] },
  { key: 'traverse-rod', name: 'Traverse Rod', category: 'hardware', subcategory: 'Rod', svgHint: 'generic',
    measurementPoints: ['Rod Width', 'One-way or Center-draw', 'Cord Side'],
    fabricSections: [] },
  { key: 'ceiling-track', name: 'Ceiling Track System', category: 'hardware', subcategory: 'Track', svgHint: 'generic',
    measurementPoints: ['Track Length', 'Curve (straight/bay/L)', 'Mount Type'],
    fabricSections: [] },
  { key: 'motorized-track', name: 'Motorized Track', category: 'hardware', subcategory: 'Smart', svgHint: 'generic',
    measurementPoints: ['Track Length', 'Motor Side', 'Power Source', 'Smart Hub Compatible'],
    fabricSections: [] },
  { key: 'holdback', name: 'Holdback / Tieback', category: 'hardware', subcategory: 'Accessory', svgHint: 'generic',
    measurementPoints: ['Style', 'Finish', 'Projection'],
    fabricSections: [] },
  { key: 'fabric-tieback', name: 'Fabric Tieback', category: 'accessory', subcategory: 'Tieback', svgHint: 'generic',
    measurementPoints: ['Length', 'Width', 'Style (rope/tassel/fabric)'],
    fabricSections: ['Tieback Body', 'Trim/Tassel'] },
  { key: 'tassel-tieback', name: 'Tassel Tieback', category: 'accessory', subcategory: 'Tieback', svgHint: 'generic',
    measurementPoints: ['Overall Length', 'Tassel Length', 'Cord Length', 'Color'],
    fabricSections: [] },

  // ─────────────────────────────────────────────────────────────
  // ACCESSORIES (10+)
  // ─────────────────────────────────────────────────────────────
  { key: 'trim-tape', name: 'Decorative Trim / Tape', category: 'accessory', subcategory: 'Trim', svgHint: 'generic',
    measurementPoints: ['Total Yardage', 'Width', 'Pattern Repeat'],
    fabricSections: ['Trim Body'] },
  { key: 'fringe', name: 'Fringe (Bullion/Brush/Bead)', category: 'accessory', subcategory: 'Trim', svgHint: 'generic',
    measurementPoints: ['Total Yardage', 'Drop Length', 'Type'],
    fabricSections: ['Fringe Body'] },
  { key: 'cord-with-lip', name: 'Cord with Lip / Welting', category: 'accessory', subcategory: 'Trim', svgHint: 'generic',
    measurementPoints: ['Total Yardage', 'Cord Diameter'],
    fabricSections: ['Cord', 'Lip'] },
  { key: 'gimp-braid', name: 'Gimp / Braid', category: 'accessory', subcategory: 'Trim', svgHint: 'generic',
    measurementPoints: ['Total Yardage', 'Width'],
    fabricSections: ['Braid Body'] },
  { key: 'rosette', name: 'Rosette', category: 'accessory', subcategory: 'Accent', svgHint: 'generic',
    measurementPoints: ['Diameter', 'Style', 'Quantity'],
    fabricSections: ['Rosette Body'] },
];
